import fs from 'fs/promises';
import path from 'path';
import { glob } from 'glob';
import { fileURLToPath } from 'url';

// --- Configuration ---
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..'); // projectRoot is /frontend directory
const modulesDir = path.join(projectRoot, 'src', 'modules'); // path is /frontend/src/modules
const outputFile = path.join(projectRoot, 'src', 'auto-modules.ts');

// --- Helper Functions ---
async function findModuleDirectories() {
  console.log(`Searching for module directories in: ${modulesDir}`);
  const directories = await glob(`${modulesDir}/*`, { absolute: true });
  
  console.log(`Glob found ${directories.length} items:`);
  directories.forEach(dir => console.log(`  - ${dir}`));
  
  // Filter directories (need to handle async properly)
  const moduleDirs: string[] = [];
  for (const dir of directories) {
    const stat = await fs.stat(dir);
    if (stat.isDirectory()) {
      console.log(`✓ Directory: ${path.basename(dir)} (${dir})`);
      moduleDirs.push(dir);
    } else {
      console.log(`✗ Not directory: ${path.basename(dir)} (${dir})`);
    }
  }
  
  console.log(`Found ${moduleDirs.length} module directories.`);
  return moduleDirs;
}

async function checkDisableFile(modulePath) {
  try {
    const disableFilePath = path.join(modulePath, '.disable');
    try {
      await fs.access(disableFilePath);
      console.log(`  🔴 Module DISABLED (has .disable file): ${path.basename(modulePath)}`);
      return false; // .disable file exists, module is disabled
    } catch (error) {
      console.log(`  🟢 Module ENABLED (no .disable file): ${path.basename(modulePath)}`);
      return true; // .disable file doesn't exist, module is enabled
    }
  } catch (error) {
    console.error(`Error checking .disable file for ${modulePath}:`, error);
    return true; // Default to enabled if there's an error
  }
}

function generateTsContent(modulesConfig) {
  // Convert to string with proper formatting
  const configString = JSON.stringify(modulesConfig, null, 4)
    // Replace double quotes around keys with no quotes if they are valid identifiers
    //.replace(/"([^"]+)":/g, '$1:')
    .replace(/"(\b[a-zA-Z_][a-zA-Z0-9_]*\b)":/g, '$1:')
    // Replace double quotes in strings with single quotes for cleaner TS
    .replace(/"/g, "'");

  return `// This file is auto-generated by scripts/generate-auto-modules.ts
// Do not edit this file directly.

// Define the module config interface
interface ModuleConfig {
    path: string;
    published: boolean;
}

// Define the modules config interface
interface ModulesConfig {
    [key: string]: ModuleConfig;
}

export const modulesConfig: ModulesConfig = ${configString};

/**
 * Get published modules
 * Returns array of module entries
 */
export function getPublishedModules(): [string, ModuleConfig][] {
    return Object.entries(modulesConfig)
        .filter(([_, config]) => config.published);
}
`;
}

async function writeModulesFile(modulesConfig) {
  try {
    const tsContent = generateTsContent(modulesConfig);
    await fs.writeFile(outputFile, tsContent, 'utf-8');
    console.log(`Successfully generated modules config file: ${outputFile}`);
  } catch (error) {
    console.error(`Error writing modules config file:`, error);
  }
}

// --- Main Logic ---
async function generateModulesConfig() {
  console.log('Starting modules config generation...');
  const moduleDirs = await findModuleDirectories();
  const modulesConfig = {};

  console.log('\nProcessing modules:');
  for (const dir of moduleDirs) {
    const moduleName = path.basename(dir);
    console.log(`\nProcessing module: ${moduleName}`);
    console.log(`  Path: ${dir}`);
    
    const isPublished = await checkDisableFile(dir);
    
    modulesConfig[moduleName] = {
      path: `/modules/${moduleName}`,
      published: isPublished,
    };
    
    console.log(`  Config: { path: "/modules/${moduleName}", published: ${isPublished} }`);
  }

  console.log('\nFinal modules config:');
  console.log(JSON.stringify(modulesConfig, null, 2));

  await writeModulesFile(modulesConfig);
  console.log('Modules config generation finished.');
}

generateModulesConfig().catch(error => {
  console.error('Modules config generation failed:', error);
  process.exit(1);
});