// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T05:19:00.692Z
export * from './types/index.js';

export interface IAuthEmailVerification {
  id: string;
  token: string;
  expiresAt: Date;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthEmailVerificationFields {
  export const id = 'id';
  export const token = 'token';
  export const expiresAt = 'expiresAt';
  export const userId = 'userId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IAuthHistory {
  id: number;
  login?: string;
  email?: string;
  password?: string;
  deviceData?: Record<string, any>;
  ispData?: Record<string, any>;
  result?: string;
  userId?: number;
  userName?: string;
  googleId?: string;
  avatar?: string;
  token: string;
  attemptTime?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace AuthHistoryFields {
  export const id = 'id';
  export const login = 'login';
  export const email = 'email';
  export const password = 'password';
  export const deviceData = 'deviceData';
  export const ispData = 'ispData';
  export const result = 'result';
  export const userId = 'userId';
  export const userName = 'userName';
  export const googleId = 'googleId';
  export const avatar = 'avatar';
  export const token = 'token';
  export const attemptTime = 'attemptTime';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface IAuthPasswordReset {
  id: string;
  userId: number;
  token: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthPasswordResetFields {
  export const id = 'id';
  export const userId = 'userId';
  export const token = 'token';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IAuthRefreshToken {
  id: string;
  userId: number;
  token: string;
  accessTokenJti?: string;
  expiresAt: Date;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace AuthRefreshTokenFields {
  export const id = 'id';
  export const userId = 'userId';
  export const token = 'token';
  export const accessTokenJti = 'accessTokenJti';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface IAuthRole {
  id: number;
  name: string;
  description: string;
  deleted?: boolean;
  abilityRules?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthRoleFields {
  export const id = 'id';
  export const name = 'name';
  export const description = 'description';
  export const deleted = 'deleted';
  export const abilityRules = 'abilityRules';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IAuthUserRole {
  userId: number;
  roleId: number;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthUserRoleFields {
  export const userId = 'userId';
  export const roleId = 'roleId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IAuthUser {
  id: number;
  isApproved?: boolean;
  isDeleted?: boolean;
  userName?: string;
  email: string;
  password: string;
  phoneNumber?: string;
  avatarUrl?: string;
  notes?: string;
  otp?: string;
  role?: string;
  dateOfBirth?: Date;
  isAdmin?: boolean;
  verificationToken?: string;
  isEmailVerified?: boolean;
  lastName?: string;
  middleName?: string;
  firstName?: string;
  googleId?: string;
  lastLoginAttempt?: Date;
  lastLogin?: Date;
  lastActivity?: Date;
  cardNumber?: string;
  twoFactorSecret?: string;
  isTwoFactorEnabled?: boolean;
  twoFactorMethod?: string;
  twoFactorTempSecret?: string;
  twoFactorTempMethod?: string;
  twoFactorTempExpiry?: Date;
  emailNotifications?: boolean;
  pushNotifications?: boolean;
  telegramNotifications?: boolean;
  telegramChatId?: string;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace AuthUserFields {
  export const id = 'id';
  export const isApproved = 'isApproved';
  export const isDeleted = 'isDeleted';
  export const userName = 'userName';
  export const email = 'email';
  export const password = 'password';
  export const phoneNumber = 'phoneNumber';
  export const avatarUrl = 'avatarUrl';
  export const notes = 'notes';
  export const otp = 'otp';
  export const role = 'role';
  export const dateOfBirth = 'dateOfBirth';
  export const isAdmin = 'isAdmin';
  export const verificationToken = 'verificationToken';
  export const isEmailVerified = 'isEmailVerified';
  export const lastName = 'lastName';
  export const middleName = 'middleName';
  export const firstName = 'firstName';
  export const googleId = 'googleId';
  export const lastLoginAttempt = 'lastLoginAttempt';
  export const lastLogin = 'lastLogin';
  export const lastActivity = 'lastActivity';
  export const cardNumber = 'cardNumber';
  export const twoFactorSecret = 'twoFactorSecret';
  export const isTwoFactorEnabled = 'isTwoFactorEnabled';
  export const twoFactorMethod = 'twoFactorMethod';
  export const twoFactorTempSecret = 'twoFactorTempSecret';
  export const twoFactorTempMethod = 'twoFactorTempMethod';
  export const twoFactorTempExpiry = 'twoFactorTempExpiry';
  export const emailNotifications = 'emailNotifications';
  export const pushNotifications = 'pushNotifications';
  export const telegramNotifications = 'telegramNotifications';
  export const telegramChatId = 'telegramChatId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface IAuthVerificationCode {
  id: string;
  email: string;
  code: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthVerificationCodeFields {
  export const id = 'id';
  export const email = 'email';
  export const code = 'code';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ICmsCategory {
  id: number;
  name: string;
  slug: string;
  parentId?: number;
  layout?: string;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

export namespace CmsCategoryFields {
  export const id = 'id';
  export const name = 'name';
  export const slug = 'slug';
  export const parentId = 'parentId';
  export const layout = 'layout';
  export const description = 'description';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ICmsItemCategory {
  itemId: number;
  categoryId: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsItemCategoryFields {
  export const itemId = 'itemId';
  export const categoryId = 'categoryId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ICmsItemMedia {
  itemId: number;
  mediaId: number;
  relationship: any;
  orderIndex?: number;
  createdAt: Date;
  updatedAt: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsItemMediaFields {
  export const itemId = 'itemId';
  export const mediaId = 'mediaId';
  export const relationship = 'relationship';
  export const orderIndex = 'orderIndex';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ICmsItemTag {
  itemId: number;
  tagId: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsItemTagFields {
  export const itemId = 'itemId';
  export const tagId = 'tagId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ICmsItemType {
  id: number;
  name: string;
  displayName: string;
  description?: string;
  schema?: Record<string, any>;
  icon?: string;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsItemTypeFields {
  export const id = 'id';
  export const name = 'name';
  export const displayName = 'displayName';
  export const description = 'description';
  export const schema = 'schema';
  export const icon = 'icon';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ICmsItem {
  id: number;
  title: string;
  slug: string;
  contentType: string;
  content?: any;
  status: string;
  layout?: string;
  sitePath: string;
  metadata?: Record<string, any>;
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string;
  canonicalUrl?: string;
  robotsMeta?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageId?: number;
  schemaType?: string;
  structuredData?: Record<string, any>;
  sitemapPriority?: any;
  sitemapChangefreq?: string;
  includeInSitemap?: boolean;
  cacheEnabled?: boolean;
  cacheTtl?: number;
  cacheInfo?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  publishAt?: Date;
  scheduledBy?: number;
  isPublic: boolean;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsItemFields {
  export const id = 'id';
  export const title = 'title';
  export const slug = 'slug';
  export const contentType = 'contentType';
  export const content = 'content';
  export const status = 'status';
  export const layout = 'layout';
  export const sitePath = 'sitePath';
  export const metadata = 'metadata';
  export const metaTitle = 'metaTitle';
  export const metaDescription = 'metaDescription';
  export const metaKeywords = 'metaKeywords';
  export const canonicalUrl = 'canonicalUrl';
  export const robotsMeta = 'robotsMeta';
  export const ogTitle = 'ogTitle';
  export const ogDescription = 'ogDescription';
  export const ogImageId = 'ogImageId';
  export const schemaType = 'schemaType';
  export const structuredData = 'structuredData';
  export const sitemapPriority = 'sitemapPriority';
  export const sitemapChangefreq = 'sitemapChangefreq';
  export const includeInSitemap = 'includeInSitemap';
  export const cacheEnabled = 'cacheEnabled';
  export const cacheTtl = 'cacheTtl';
  export const cacheInfo = 'cacheInfo';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const publishedAt = 'publishedAt';
  export const publishAt = 'publishAt';
  export const scheduledBy = 'scheduledBy';
  export const isPublic = 'isPublic';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ICmsMedia {
  id: number;
  filename: string;
  originalFilename: string;
  mimeType: string;
  size: number;
  path: string;
  altText?: string;
  title?: string;
  description?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsMediaFields {
  export const id = 'id';
  export const filename = 'filename';
  export const originalFilename = 'originalFilename';
  export const mimeType = 'mimeType';
  export const size = 'size';
  export const path = 'path';
  export const altText = 'altText';
  export const title = 'title';
  export const description = 'description';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ICmsTag {
  id: number;
  name: string;
  slug: string;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsTagFields {
  export const id = 'id';
  export const name = 'name';
  export const slug = 'slug';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface IDispatcherQueueTask {
  id: number;
  queue: string;
  type: string;
  name: string;
  data: Record<string, any>;
  status: string;
  priority: number;
  attempts: number;
  maxAttempts: number;
  error?: string;
  createdAt: Date;
  updatedAt: Date;
  processedAt?: Date;
}

export namespace DispatcherQueueTaskFields {
  export const id = 'id';
  export const queue = 'queue';
  export const type = 'type';
  export const name = 'name';
  export const data = 'data';
  export const status = 'status';
  export const priority = 'priority';
  export const attempts = 'attempts';
  export const maxAttempts = 'maxAttempts';
  export const error = 'error';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const processedAt = 'processedAt';
}

export interface IDispatcherTaskHistory {
  id: number;
  taskId?: number;
  parentId?: number;
  taskName?: string;
  taskType?: string;
  queueName?: string;
  status: string;
  externalJobId?: string;
  waitingSince?: Date;
  waitingUntil?: Date;
  startedAt: Date;
  finishedAt?: Date;
  duration?: number;
  error?: string;
  result?: Record<string, any>;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt: Date;
  createdBy?: number;
}

export namespace DispatcherTaskHistoryFields {
  export const id = 'id';
  export const taskId = 'taskId';
  export const parentId = 'parentId';
  export const taskName = 'taskName';
  export const taskType = 'taskType';
  export const queueName = 'queueName';
  export const status = 'status';
  export const externalJobId = 'externalJobId';
  export const waitingSince = 'waitingSince';
  export const waitingUntil = 'waitingUntil';
  export const startedAt = 'startedAt';
  export const finishedAt = 'finishedAt';
  export const duration = 'duration';
  export const error = 'error';
  export const result = 'result';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
}

export interface IDispatcherTask {
  id: number;
  name: string;
  type: string;
  data?: Record<string, any>;
  periodSec?: number;
  parentId?: number;
  isActive: boolean;
  lastRun?: Date;
  lastStatus?: string;
  lastError?: string;
  maxRuns?: number;
  runCount?: number;
  nextRun?: Date;
  scheduleType?: string;
  cronExpr?: string;
  timeout?: number;
  retryCount?: number;
  retryDelay?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace DispatcherTaskFields {
  export const id = 'id';
  export const name = 'name';
  export const type = 'type';
  export const data = 'data';
  export const periodSec = 'periodSec';
  export const parentId = 'parentId';
  export const isActive = 'isActive';
  export const lastRun = 'lastRun';
  export const lastStatus = 'lastStatus';
  export const lastError = 'lastError';
  export const maxRuns = 'maxRuns';
  export const runCount = 'runCount';
  export const nextRun = 'nextRun';
  export const scheduleType = 'scheduleType';
  export const cronExpr = 'cronExpr';
  export const timeout = 'timeout';
  export const retryCount = 'retryCount';
  export const retryDelay = 'retryDelay';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface INotificationsHistory {
  id: number;
  userId: number;
  type: string;
  message: any;
  status: string;
  metadata?: Record<string, any>;
  templateId?: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace NotificationsHistoryFields {
  export const id = 'id';
  export const userId = 'userId';
  export const type = 'type';
  export const message = 'message';
  export const status = 'status';
  export const metadata = 'metadata';
  export const templateId = 'templateId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface INotificationsTelegramUser {
  id: number;
  phone: string;
  chatId: string;
  username?: string;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace NotificationsTelegramUserFields {
  export const id = 'id';
  export const phone = 'phone';
  export const chatId = 'chatId';
  export const username = 'username';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface INotificationsTemplate {
  id: number;
  name: string;
  subject: string;
  body: any;
  notificationType: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace NotificationsTemplateFields {
  export const id = 'id';
  export const name = 'name';
  export const subject = 'subject';
  export const body = 'body';
  export const notificationType = 'notificationType';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface IStorageFile {
  id: string;
  originalName: string;
  fileName: string;
  mimeType: string;
  size: number;
  storageProvider: string;
  storagePath: string;
  publicUrl?: string;
  visibility: string;
  userId: number;
  moduleContext?: string;
  contextId?: string;
  tags?: Record<string, any>;
  description?: string;
  status: string;
  expiresAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

export namespace StorageFileFields {
  export const id = 'id';
  export const originalName = 'originalName';
  export const fileName = 'fileName';
  export const mimeType = 'mimeType';
  export const size = 'size';
  export const storageProvider = 'storageProvider';
  export const storagePath = 'storagePath';
  export const publicUrl = 'publicUrl';
  export const visibility = 'visibility';
  export const userId = 'userId';
  export const moduleContext = 'moduleContext';
  export const contextId = 'contextId';
  export const tags = 'tags';
  export const description = 'description';
  export const status = 'status';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const deletedAt = 'deletedAt';
}

export interface IConfigPublic {
  id: number;
  key: string;
  value: any;
  category?: string;
  dataType?: string;
  description?: any;
  createdAt: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ConfigPublicFields {
  export const id = 'id';
  export const key = 'key';
  export const value = 'value';
  export const category = 'category';
  export const dataType = 'dataType';
  export const description = 'description';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface IServerContainer {
  id: number;
  name: string;
  projectId: number;
  status: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ServerContainerFields {
  export const id = 'id';
  export const name = 'name';
  export const projectId = 'projectId';
  export const status = 'status';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface IServerProject {
  id: number;
  name: string;
  description?: any;
  status: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ServerProjectFields {
  export const id = 'id';
  export const name = 'name';
  export const description = 'description';
  export const status = 'status';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ISystemCache {
  id: number;
  key: string;
  value: any;
  namespace?: string;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt?: Date;
}

export namespace SystemCacheFields {
  export const id = 'id';
  export const key = 'key';
  export const value = 'value';
  export const namespace = 'namespace';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ISystemConfigAudit {
  id: number;
  configKey: string;
  oldValue?: any;
  newValue?: any;
  changedBy?: number;
  changeSource: string;
  ipAddress?: string;
  userAgent?: any;
  createdAt: Date;
  updatedAt: Date;
}

export namespace SystemConfigAuditFields {
  export const id = 'id';
  export const configKey = 'configKey';
  export const oldValue = 'oldValue';
  export const newValue = 'newValue';
  export const changedBy = 'changedBy';
  export const changeSource = 'changeSource';
  export const ipAddress = 'ipAddress';
  export const userAgent = 'userAgent';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ISystemConfig {
  id: number;
  key: string;
  value: any;
  category?: string;
  dataType?: string;
  isEncrypted?: boolean;
  requiresRestart?: boolean;
  description?: any;
  createdAt: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemConfigFields {
  export const id = 'id';
  export const key = 'key';
  export const value = 'value';
  export const category = 'category';
  export const dataType = 'dataType';
  export const isEncrypted = 'isEncrypted';
  export const requiresRestart = 'requiresRestart';
  export const description = 'description';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ISystemDynamicRoute {
  id: string;
  path: string;
  name: string;
  component?: string;
  parentId?: string;
  orderIndex: number;
  meta?: Record<string, any>;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemDynamicRouteFields {
  export const id = 'id';
  export const path = 'path';
  export const name = 'name';
  export const component = 'component';
  export const parentId = 'parentId';
  export const orderIndex = 'orderIndex';
  export const meta = 'meta';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ISystemError {
  id: number;
  logId: number;
  errorType: string;
  errorMessage: any;
  stackTrace?: any;
  additionalData?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemErrorFields {
  export const id = 'id';
  export const logId = 'logId';
  export const errorType = 'errorType';
  export const errorMessage = 'errorMessage';
  export const stackTrace = 'stackTrace';
  export const additionalData = 'additionalData';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ISystemLogStat {
  id: number;
  date: Date;
  hour: number;
  source: string;
  module: string;
  level: string;
  count: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemLogStatFields {
  export const id = 'id';
  export const date = 'date';
  export const hour = 'hour';
  export const source = 'source';
  export const module = 'module';
  export const level = 'level';
  export const count = 'count';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ISystemLog {
  id: number;
  timestamp: Date;
  level: string;
  source: string;
  component: string;
  module: string;
  message: any;
  metadata?: Record<string, any>;
  contextId?: string;
  userId?: string;
  ipAddress?: string;
  requestPath?: string;
  requestMethod?: string;
  executionTime?: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemLogFields {
  export const id = 'id';
  export const timestamp = 'timestamp';
  export const level = 'level';
  export const source = 'source';
  export const component = 'component';
  export const module = 'module';
  export const message = 'message';
  export const metadata = 'metadata';
  export const contextId = 'contextId';
  export const userId = 'userId';
  export const ipAddress = 'ipAddress';
  export const requestPath = 'requestPath';
  export const requestMethod = 'requestMethod';
  export const executionTime = 'executionTime';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ISystemSessionStorage {
  id: number;
  key: string;
  value: any;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export namespace SystemSessionStorageFields {
  export const id = 'id';
  export const key = 'key';
  export const value = 'value';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IAiAgentConversation {
  id?: number;
  userId: number;
  title?: string;
  messages: Record<string, any>;
  context: string;
  status: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace AiAgentConversationFields {
  export const id = 'id';
  export const userId = 'userId';
  export const title = 'title';
  export const messages = 'messages';
  export const context = 'context';
  export const status = 'status';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IAiAgentOperation {
  id?: number;
  operationId: string;
  parameters: Record<string, any>;
  result: Record<string, any>;
  userId: number;
  source: string;
  conversationId?: number;
  duration: number;
  status: string;
  executedAt?: Date;
}

export namespace AiAgentOperationFields {
  export const id = 'id';
  export const operationId = 'operationId';
  export const parameters = 'parameters';
  export const result = 'result';
  export const userId = 'userId';
  export const source = 'source';
  export const conversationId = 'conversationId';
  export const duration = 'duration';
  export const status = 'status';
  export const executedAt = 'executedAt';
}

export interface IAiAgentSession {
  id?: number;
  visitorId: string;
  userId?: number;
  messages: Record<string, any>;
  memoryBuffer: Record<string, any>;
  agentState: Record<string, any>;
  status: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace AiAgentSessionFields {
  export const id = 'id';
  export const visitorId = 'visitorId';
  export const userId = 'userId';
  export const messages = 'messages';
  export const memoryBuffer = 'memoryBuffer';
  export const agentState = 'agentState';
  export const status = 'status';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IKnowledgeDocument {
  id?: number;
  siteId?: string;
  category: string;
  key: string;
  title: string;
  content: any;
  structuredView?: any;
  metadata?: Record<string, any>;
  tags?: Record<string, any>;
  source?: string;
  scannedAt?: Date;
  isActive?: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export namespace KnowledgeDocumentFields {
  export const id = 'id';
  export const siteId = 'siteId';
  export const category = 'category';
  export const key = 'key';
  export const title = 'title';
  export const content = 'content';
  export const structuredView = 'structuredView';
  export const metadata = 'metadata';
  export const tags = 'tags';
  export const source = 'source';
  export const scannedAt = 'scannedAt';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ICompassItem {
  id: number;
  userId: number;
  type: string;
  approach?: string;
  parentId?: number;
  level: number;
  title: string;
  description?: any;
  status: string;
  deadline?: Date;
  startDate?: Date;
  completedAt?: Date;
  progress: number;
  metrics?: any;
  quarter?: string;
  phase?: string;
  position: number;
  tags?: any;
  priority?: string;
  workflowId?: number;
  executionType?: string;
  linkedPlanId?: number;
  partOfItemId?: number;
  aiAnalysis?: any;
  isCritical: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CompassItemFields {
  export const id = 'id';
  export const userId = 'userId';
  export const type = 'type';
  export const approach = 'approach';
  export const parentId = 'parentId';
  export const level = 'level';
  export const title = 'title';
  export const description = 'description';
  export const status = 'status';
  export const deadline = 'deadline';
  export const startDate = 'startDate';
  export const completedAt = 'completedAt';
  export const progress = 'progress';
  export const metrics = 'metrics';
  export const quarter = 'quarter';
  export const phase = 'phase';
  export const position = 'position';
  export const tags = 'tags';
  export const priority = 'priority';
  export const workflowId = 'workflowId';
  export const executionType = 'executionType';
  export const linkedPlanId = 'linkedPlanId';
  export const partOfItemId = 'partOfItemId';
  export const aiAnalysis = 'aiAnalysis';
  export const isCritical = 'isCritical';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ICrmChannel {
  id?: number;
  name: string;
  type: string;
  config?: Record<string, any>;
  isActive?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CrmChannelFields {
  export const id = 'id';
  export const name = 'name';
  export const type = 'type';
  export const config = 'config';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ICrmContact {
  id?: number;
  name: string;
  email?: string;
  phone?: string;
  newsletterStatus?: string;
  source?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CrmContactFields {
  export const id = 'id';
  export const name = 'name';
  export const email = 'email';
  export const phone = 'phone';
  export const newsletterStatus = 'newsletterStatus';
  export const source = 'source';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ICrmConversation {
  id?: number;
  contactId: number;
  subject: string;
  status?: string;
  priority?: string;
  assignedTo?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CrmConversationFields {
  export const id = 'id';
  export const contactId = 'contactId';
  export const subject = 'subject';
  export const status = 'status';
  export const priority = 'priority';
  export const assignedTo = 'assignedTo';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ICrmMessage {
  id?: number;
  conversationId: number;
  channelId?: number;
  type: string;
  direction: string;
  content: any;
  metadata?: Record<string, any>;
  status?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CrmMessageFields {
  export const id = 'id';
  export const conversationId = 'conversationId';
  export const channelId = 'channelId';
  export const type = 'type';
  export const direction = 'direction';
  export const content = 'content';
  export const metadata = 'metadata';
  export const status = 'status';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ICrmTouchpoint {
  id?: number;
  contactId: number;
  source: string;
  channel?: string;
  action: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
}

export namespace CrmTouchpointFields {
  export const id = 'id';
  export const contactId = 'contactId';
  export const source = 'source';
  export const channel = 'channel';
  export const action = 'action';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
}

export interface IImageUpload {
  id: number;
  fileName: string;
  originalName: string;
  mimeType: string;
  size: number;
  url: string;
  isActive: boolean;
  createdAt?: Date;
  createdBy?: number;
  updatedAt?: Date;
  updatedBy?: number;
}

export namespace ImageUploadFields {
  export const id = 'id';
  export const fileName = 'fileName';
  export const originalName = 'originalName';
  export const mimeType = 'mimeType';
  export const size = 'size';
  export const url = 'url';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const createdBy = 'createdBy';
  export const updatedAt = 'updatedAt';
  export const updatedBy = 'updatedBy';
}

export interface INewsletterCampaign {
  id?: number;
  name: string;
  templateId: number;
  status?: string;
  recipientFilter?: Record<string, any>;
  totalRecipients?: number;
  sentCount?: number;
  failedCount?: number;
  openCount?: number;
  clickCount?: number;
  scheduledAt?: Date;
  startedAt?: Date;
  completedAt?: Date;
  createdBy?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace NewsletterCampaignFields {
  export const id = 'id';
  export const name = 'name';
  export const templateId = 'templateId';
  export const status = 'status';
  export const recipientFilter = 'recipientFilter';
  export const totalRecipients = 'totalRecipients';
  export const sentCount = 'sentCount';
  export const failedCount = 'failedCount';
  export const openCount = 'openCount';
  export const clickCount = 'clickCount';
  export const scheduledAt = 'scheduledAt';
  export const startedAt = 'startedAt';
  export const completedAt = 'completedAt';
  export const createdBy = 'createdBy';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface INewsletterEmailLog {
  id?: number;
  campaignId: number;
  subscriptionId: number;
  email: string;
  status?: string;
  sentAt?: Date;
  openedAt?: Date;
  clickedAt?: Date;
  errorMessage?: any;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace NewsletterEmailLogFields {
  export const id = 'id';
  export const campaignId = 'campaignId';
  export const subscriptionId = 'subscriptionId';
  export const email = 'email';
  export const status = 'status';
  export const sentAt = 'sentAt';
  export const openedAt = 'openedAt';
  export const clickedAt = 'clickedAt';
  export const errorMessage = 'errorMessage';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface INewsletterTemplate {
  id?: number;
  name: string;
  subject: string;
  previewText?: string;
  htmlContent: any;
  textContent?: any;
  status?: string;
  category?: string;
  variables?: Record<string, any>;
  createdBy?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace NewsletterTemplateFields {
  export const id = 'id';
  export const name = 'name';
  export const subject = 'subject';
  export const previewText = 'previewText';
  export const htmlContent = 'htmlContent';
  export const textContent = 'textContent';
  export const status = 'status';
  export const category = 'category';
  export const variables = 'variables';
  export const createdBy = 'createdBy';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface INewsletterSubscription {
  id?: number;
  email: string;
  name?: string;
  status?: string;
  isActive?: boolean;
  source?: string;
  tags?: Record<string, any>;
  unsubscribeToken?: string;
  unsubscribedAt?: Date;
  ipAddress?: string;
  userAgent?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace NewsletterSubscriptionFields {
  export const id = 'id';
  export const email = 'email';
  export const name = 'name';
  export const status = 'status';
  export const isActive = 'isActive';
  export const source = 'source';
  export const tags = 'tags';
  export const unsubscribeToken = 'unsubscribeToken';
  export const unsubscribedAt = 'unsubscribedAt';
  export const ipAddress = 'ipAddress';
  export const userAgent = 'userAgent';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPaymentFeatureCost {
  id?: number;
  featureId: string;
  name: string;
  description?: any;
  pluginId: string;
  defaultCost: number;
  tierCosts?: Record<string, any>;
  category?: string;
  active: boolean;
  minimumTier?: string;
  trackUsage: boolean;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentFeatureCostFields {
  export const id = 'id';
  export const featureId = 'featureId';
  export const name = 'name';
  export const description = 'description';
  export const pluginId = 'pluginId';
  export const defaultCost = 'defaultCost';
  export const tierCosts = 'tierCosts';
  export const category = 'category';
  export const active = 'active';
  export const minimumTier = 'minimumTier';
  export const trackUsage = 'trackUsage';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPaymentProduct {
  id?: number;
  productId: string;
  name: string;
  description?: any;
  type: string;
  price: any;
  tokenGrant?: number;
  bonus?: number;
  popular: boolean;
  featured: boolean;
  stripePriceId?: string;
  active: boolean;
  sortOrder: number;
  imageUrl?: string;
  featureAccess?: Record<string, any>;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentProductFields {
  export const id = 'id';
  export const productId = 'productId';
  export const name = 'name';
  export const description = 'description';
  export const type = 'type';
  export const price = 'price';
  export const tokenGrant = 'tokenGrant';
  export const bonus = 'bonus';
  export const popular = 'popular';
  export const featured = 'featured';
  export const stripePriceId = 'stripePriceId';
  export const active = 'active';
  export const sortOrder = 'sortOrder';
  export const imageUrl = 'imageUrl';
  export const featureAccess = 'featureAccess';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPaymentSubscription {
  id?: number;
  userId: number;
  tier: string;
  tokenBalance: number;
  status: string;
  expiresAt?: Date;
  cancelledAt?: Date;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentSubscriptionFields {
  export const id = 'id';
  export const userId = 'userId';
  export const tier = 'tier';
  export const tokenBalance = 'tokenBalance';
  export const status = 'status';
  export const expiresAt = 'expiresAt';
  export const cancelledAt = 'cancelledAt';
  export const stripeCustomerId = 'stripeCustomerId';
  export const stripeSubscriptionId = 'stripeSubscriptionId';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPaymentTokenTransaction {
  id?: number;
  userId: number;
  subscriptionId?: number;
  amount: number;
  balanceAfter: number;
  type: string;
  reason: string;
  referenceId?: string;
  idempotencyKey?: string;
  stripePaymentIntentId?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentTokenTransactionFields {
  export const id = 'id';
  export const userId = 'userId';
  export const subscriptionId = 'subscriptionId';
  export const amount = 'amount';
  export const balanceAfter = 'balanceAfter';
  export const type = 'type';
  export const reason = 'reason';
  export const referenceId = 'referenceId';
  export const idempotencyKey = 'idempotencyKey';
  export const stripePaymentIntentId = 'stripePaymentIntentId';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPaymentPricingTierConfig {
  id?: number;
  tier: string;
  name: string;
  description?: any;
  price: any;
  interval: string;
  tokenGrant: number;
  tokenRefill: number;
  rollover: boolean;
  features?: Record<string, any>;
  stripePriceId?: string;
  active: boolean;
  sortOrder: number;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentPricingTierConfigFields {
  export const id = 'id';
  export const tier = 'tier';
  export const name = 'name';
  export const description = 'description';
  export const price = 'price';
  export const interval = 'interval';
  export const tokenGrant = 'tokenGrant';
  export const tokenRefill = 'tokenRefill';
  export const rollover = 'rollover';
  export const features = 'features';
  export const stripePriceId = 'stripePriceId';
  export const active = 'active';
  export const sortOrder = 'sortOrder';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPaymentUsageLog {
  id?: number;
  userId: number;
  resourceType: string;
  amount: number;
  endpoint?: string;
  metadata?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

export namespace PaymentUsageLogFields {
  export const id = 'id';
  export const userId = 'userId';
  export const resourceType = 'resourceType';
  export const amount = 'amount';
  export const endpoint = 'endpoint';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPaymentUsageQuota {
  id?: number;
  userId: number;
  resourceType: string;
  quotaLimit: number;
  currentUsage: number;
  resetAt: Date;
  tier: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentUsageQuotaFields {
  export const id = 'id';
  export const userId = 'userId';
  export const resourceType = 'resourceType';
  export const quotaLimit = 'quotaLimit';
  export const currentUsage = 'currentUsage';
  export const resetAt = 'resetAt';
  export const tier = 'tier';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPhotoshootImage {
  id: number;
  sessionId: number;
  styleConfig: Record<string, any>;
  storageFileId?: string;
  taskHistoryId?: number;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PhotoshootImageFields {
  export const id = 'id';
  export const sessionId = 'sessionId';
  export const styleConfig = 'styleConfig';
  export const storageFileId = 'storageFileId';
  export const taskHistoryId = 'taskHistoryId';
  export const status = 'status';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IPhotoshootSession {
  id: number;
  userId: number;
  packageConfig: Record<string, any>;
  uploadedPhotoIds: Record<string, any>;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  totalImages: number;
  completedImages: number;
  taskIds: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PhotoshootSessionFields {
  export const id = 'id';
  export const userId = 'userId';
  export const packageConfig = 'packageConfig';
  export const uploadedPhotoIds = 'uploadedPhotoIds';
  export const status = 'status';
  export const totalImages = 'totalImages';
  export const completedImages = 'completedImages';
  export const taskIds = 'taskIds';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IProjectActivity {
  id: number;
  projectId: number;
  taskId?: number;
  entityType: string;
  action: string;
  field?: string;
  oldValue?: any;
  newValue?: any;
  description?: any;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
}

export namespace ProjectActivityFields {
  export const id = 'id';
  export const projectId = 'projectId';
  export const taskId = 'taskId';
  export const entityType = 'entityType';
  export const action = 'action';
  export const field = 'field';
  export const oldValue = 'oldValue';
  export const newValue = 'newValue';
  export const description = 'description';
  export const userId = 'userId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IProjectTask {
  id: number;
  projectId: number;
  parentTaskId?: number;
  title: string;
  description?: any;
  status: string;
  priority: string;
  assigneeId?: number;
  deadline?: Date;
  completedAt?: Date;
  estimatedHours?: any;
  actualHours?: any;
  position?: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ProjectTaskFields {
  export const id = 'id';
  export const projectId = 'projectId';
  export const parentTaskId = 'parentTaskId';
  export const title = 'title';
  export const description = 'description';
  export const status = 'status';
  export const priority = 'priority';
  export const assigneeId = 'assigneeId';
  export const deadline = 'deadline';
  export const completedAt = 'completedAt';
  export const estimatedHours = 'estimatedHours';
  export const actualHours = 'actualHours';
  export const position = 'position';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface IProject {
  id: number;
  name: string;
  slug: string;
  description?: any;
  status: string;
  priority?: string;
  startDate?: Date;
  deadline?: Date;
  completedAt?: Date;
  color?: string;
  ownerId: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ProjectFields {
  export const id = 'id';
  export const name = 'name';
  export const slug = 'slug';
  export const description = 'description';
  export const status = 'status';
  export const priority = 'priority';
  export const startDate = 'startDate';
  export const deadline = 'deadline';
  export const completedAt = 'completedAt';
  export const color = 'color';
  export const ownerId = 'ownerId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ISocialAccount {
  id: number;
  platformId: string;
  userId: number;
  accountName: string;
  accountHandle: string;
  accountId: string;
  accessToken: string;
  refreshToken?: string;
  tokenExpiresAt?: Date;
  isActive: boolean;
  lastSync?: Date;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace SocialAccountFields {
  export const id = 'id';
  export const platformId = 'platformId';
  export const userId = 'userId';
  export const accountName = 'accountName';
  export const accountHandle = 'accountHandle';
  export const accountId = 'accountId';
  export const accessToken = 'accessToken';
  export const refreshToken = 'refreshToken';
  export const tokenExpiresAt = 'tokenExpiresAt';
  export const isActive = 'isActive';
  export const lastSync = 'lastSync';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ISocialPlatform {
  id: string;
  name: string;
  displayName: string;
  icon?: string;
  maxTextLength?: number;
  supportedMediaTypes?: Record<string, any>;
  features?: Record<string, any>;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace SocialPlatformFields {
  export const id = 'id';
  export const name = 'name';
  export const displayName = 'displayName';
  export const icon = 'icon';
  export const maxTextLength = 'maxTextLength';
  export const supportedMediaTypes = 'supportedMediaTypes';
  export const features = 'features';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ISocialPostAnalytics {
  id: number;
  postId: number;
  platformId: string;
  likes?: number;
  shares?: number;
  comments?: number;
  views?: number;
  clicks?: number;
  metadata?: Record<string, any>;
  lastUpdated?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export namespace SocialPostAnalyticsFields {
  export const id = 'id';
  export const postId = 'postId';
  export const platformId = 'platformId';
  export const likes = 'likes';
  export const shares = 'shares';
  export const comments = 'comments';
  export const views = 'views';
  export const clicks = 'clicks';
  export const metadata = 'metadata';
  export const lastUpdated = 'lastUpdated';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ISocialPostMedia {
  postId: number;
  mediaId: number;
  orderIndex?: number;
  createdAt: Date;
  updatedAt: Date;
}

export namespace SocialPostMediaFields {
  export const postId = 'postId';
  export const mediaId = 'mediaId';
  export const orderIndex = 'orderIndex';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ISocialPostTemplate {
  id: number;
  name: string;
  description?: string;
  platformId: string;
  userId: number;
  content: string;
  hashtags?: Record<string, any>;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace SocialPostTemplateFields {
  export const id = 'id';
  export const name = 'name';
  export const description = 'description';
  export const platformId = 'platformId';
  export const userId = 'userId';
  export const content = 'content';
  export const hashtags = 'hashtags';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface ISocialPost {
  id: number;
  platformId: string;
  accountId: number;
  userId: number;
  content: string;
  mediaIds?: Record<string, any>;
  hashtags?: Record<string, any>;
  status: string;
  scheduledAt?: Date;
  publishedAt?: Date;
  externalPostId?: string;
  externalUrl?: string;
  metadata?: Record<string, any>;
  errorMessage?: string;
  retryCount?: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SocialPostFields {
  export const id = 'id';
  export const platformId = 'platformId';
  export const accountId = 'accountId';
  export const userId = 'userId';
  export const content = 'content';
  export const mediaIds = 'mediaIds';
  export const hashtags = 'hashtags';
  export const status = 'status';
  export const scheduledAt = 'scheduledAt';
  export const publishedAt = 'publishedAt';
  export const externalPostId = 'externalPostId';
  export const externalUrl = 'externalUrl';
  export const metadata = 'metadata';
  export const errorMessage = 'errorMessage';
  export const retryCount = 'retryCount';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}

export interface ITestItem {
  id: number;
  title: string;
  description?: any;
  count?: number;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace TestItemFields {
  export const id = 'id';
  export const title = 'title';
  export const description = 'description';
  export const count = 'count';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IWaitlistReferral {
  id: number;
  referrerId: number;
  referredEmail: string;
  status: string;
  clickedAt: Date;
  signedUpAt?: Date;
  verifiedAt?: Date;
  metadata?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

export namespace WaitlistReferralFields {
  export const id = 'id';
  export const referrerId = 'referrerId';
  export const referredEmail = 'referredEmail';
  export const status = 'status';
  export const clickedAt = 'clickedAt';
  export const signedUpAt = 'signedUpAt';
  export const verifiedAt = 'verifiedAt';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IWaitlistSignup {
  id: number;
  email: string;
  name?: string;
  status: string;
  position: number;
  referralCode: string;
  referredById?: number;
  referralCount: number;
  positionBoost: number;
  verificationToken?: string;
  verificationTokenExpiry?: Date;
  newsletterConsent: boolean;
  metadata?: Record<string, any>;
  verifiedAt?: Date;
  invitedAt?: Date;
  unsubscribedAt?: Date;
  userId?: number;
  contactId?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WaitlistSignupFields {
  export const id = 'id';
  export const email = 'email';
  export const name = 'name';
  export const status = 'status';
  export const position = 'position';
  export const referralCode = 'referralCode';
  export const referredById = 'referredById';
  export const referralCount = 'referralCount';
  export const positionBoost = 'positionBoost';
  export const verificationToken = 'verificationToken';
  export const verificationTokenExpiry = 'verificationTokenExpiry';
  export const newsletterConsent = 'newsletterConsent';
  export const metadata = 'metadata';
  export const verifiedAt = 'verifiedAt';
  export const invitedAt = 'invitedAt';
  export const unsubscribedAt = 'unsubscribedAt';
  export const userId = 'userId';
  export const contactId = 'contactId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IWebAnalyticsPageView {
  id: string;
  visitId: string;
  sessionId: string;
  userId?: number;
  source: string;
  path: string;
  queryParams?: Record<string, any>;
  referrerUrl?: string;
  referrerPath?: string;
  viewedAt: Date;
  userAgent: string;
  ipAddressHash: string;
  httpStatus?: number;
  requestTimeMs?: number;
  screenResolution?: string;
  pageTitle?: string;
  timeOnPageSeconds?: number;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WebAnalyticsPageViewFields {
  export const id = 'id';
  export const visitId = 'visitId';
  export const sessionId = 'sessionId';
  export const userId = 'userId';
  export const source = 'source';
  export const path = 'path';
  export const queryParams = 'queryParams';
  export const referrerUrl = 'referrerUrl';
  export const referrerPath = 'referrerPath';
  export const viewedAt = 'viewedAt';
  export const userAgent = 'userAgent';
  export const ipAddressHash = 'ipAddressHash';
  export const httpStatus = 'httpStatus';
  export const requestTimeMs = 'requestTimeMs';
  export const screenResolution = 'screenResolution';
  export const pageTitle = 'pageTitle';
  export const timeOnPageSeconds = 'timeOnPageSeconds';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IWebAnalyticsReferrer {
  id: number;
  referrerUrl: string;
  referrerDomain: string;
  channel: string;
  visits: number;
  uniqueVisitors: number;
  pageViews: number;
  avgSessionDuration: number;
  bounceRate: any;
  avgPagesPerVisit: any;
  firstSeenAt: Date;
  lastSeenAt: Date;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WebAnalyticsReferrerFields {
  export const id = 'id';
  export const referrerUrl = 'referrerUrl';
  export const referrerDomain = 'referrerDomain';
  export const channel = 'channel';
  export const visits = 'visits';
  export const uniqueVisitors = 'uniqueVisitors';
  export const pageViews = 'pageViews';
  export const avgSessionDuration = 'avgSessionDuration';
  export const bounceRate = 'bounceRate';
  export const avgPagesPerVisit = 'avgPagesPerVisit';
  export const firstSeenAt = 'firstSeenAt';
  export const lastSeenAt = 'lastSeenAt';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IWebAnalyticsVisit {
  id: string;
  sessionId: string;
  userId?: number;
  ipAddressHash: string;
  userAgent: string;
  deviceType: string;
  browserName?: string;
  browserVersion?: string;
  osName?: string;
  osVersion?: string;
  firstVisitAt: Date;
  lastActivityAt: Date;
  durationSeconds: number;
  entryPage: string;
  exitPage?: string;
  pageViewsCount: number;
  referrerUrl?: string;
  referrerDomain?: string;
  channel?: string;
  utmSource?: string;
  utmMedium?: string;
  utmCampaign?: string;
  utmTerm?: string;
  utmContent?: string;
  isBounce: boolean;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WebAnalyticsVisitFields {
  export const id = 'id';
  export const sessionId = 'sessionId';
  export const userId = 'userId';
  export const ipAddressHash = 'ipAddressHash';
  export const userAgent = 'userAgent';
  export const deviceType = 'deviceType';
  export const browserName = 'browserName';
  export const browserVersion = 'browserVersion';
  export const osName = 'osName';
  export const osVersion = 'osVersion';
  export const firstVisitAt = 'firstVisitAt';
  export const lastActivityAt = 'lastActivityAt';
  export const durationSeconds = 'durationSeconds';
  export const entryPage = 'entryPage';
  export const exitPage = 'exitPage';
  export const pageViewsCount = 'pageViewsCount';
  export const referrerUrl = 'referrerUrl';
  export const referrerDomain = 'referrerDomain';
  export const channel = 'channel';
  export const utmSource = 'utmSource';
  export const utmMedium = 'utmMedium';
  export const utmCampaign = 'utmCampaign';
  export const utmTerm = 'utmTerm';
  export const utmContent = 'utmContent';
  export const isBounce = 'isBounce';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IBlockExecution {
  id?: number;
  executionId: number;
  blockId: string;
  input?: Record<string, any>;
  output?: Record<string, any>;
  status: string;
  error?: any;
  startedAt?: Date;
  completedAt?: Date;
  duration?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace BlockExecutionFields {
  export const id = 'id';
  export const executionId = 'executionId';
  export const blockId = 'blockId';
  export const input = 'input';
  export const output = 'output';
  export const status = 'status';
  export const error = 'error';
  export const startedAt = 'startedAt';
  export const completedAt = 'completedAt';
  export const duration = 'duration';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

export interface IWorkflowDefinition {
  id?: number;
  name: string;
  description?: any;
  userPrompt?: any;
  masterPrompt?: any;
  version: number;
  blocks: Record<string, any>;
  connections: Record<string, any>;
  status: string;
  triggerType: string;
  triggerConfig?: Record<string, any>;
  tags?: Record<string, any>;
  isActive: boolean;
  createdBy: number;
  createdAt?: Date;
  updatedAt?: Date;
  publishedAt?: Date;
}

export namespace WorkflowDefinitionFields {
  export const id = 'id';
  export const name = 'name';
  export const description = 'description';
  export const userPrompt = 'userPrompt';
  export const masterPrompt = 'masterPrompt';
  export const version = 'version';
  export const blocks = 'blocks';
  export const connections = 'connections';
  export const status = 'status';
  export const triggerType = 'triggerType';
  export const triggerConfig = 'triggerConfig';
  export const tags = 'tags';
  export const isActive = 'isActive';
  export const createdBy = 'createdBy';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const publishedAt = 'publishedAt';
}

export interface IWorkflowExecution {
  id?: number;
  workflowId: number;
  status: string;
  currentBlocks?: Record<string, any>;
  completedBlocks?: Record<string, any>;
  failedBlocks?: Record<string, any>;
  progress: number;
  blockResults?: Record<string, any>;
  logs?: Record<string, any>;
  context?: Record<string, any>;
  startedAt?: Date;
  completedAt?: Date;
  pausedAt?: Date;
  error?: any;
  errorDetails?: Record<string, any>;
  triggeredBy?: number;
  triggerSource: string;
  retryCount: number;
  parentExecutionId?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WorkflowExecutionFields {
  export const id = 'id';
  export const workflowId = 'workflowId';
  export const status = 'status';
  export const currentBlocks = 'currentBlocks';
  export const completedBlocks = 'completedBlocks';
  export const failedBlocks = 'failedBlocks';
  export const progress = 'progress';
  export const blockResults = 'blockResults';
  export const logs = 'logs';
  export const context = 'context';
  export const startedAt = 'startedAt';
  export const completedAt = 'completedAt';
  export const pausedAt = 'pausedAt';
  export const error = 'error';
  export const errorDetails = 'errorDetails';
  export const triggeredBy = 'triggeredBy';
  export const triggerSource = 'triggerSource';
  export const retryCount = 'retryCount';
  export const parentExecutionId = 'parentExecutionId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}

