// This file is auto-generated by scripts/generate-auto-modules.ts
// Do not edit this file directly.

// Define the module config interface
interface ModuleConfig {
    path: string;
    published: boolean;
}

// Define the modules config interface
interface ModulesConfig {
    [key: string]: ModuleConfig;
}

export const modulesConfig: ModulesConfig = {
    'user-management': {
        path: '/modules/user-management',
        published: true
    },
    system: {
        path: '/modules/system',
        published: true
    },
    routes: {
        path: '/modules/routes',
        published: true
    },
    'file-manager': {
        path: '/modules/file-manager',
        published: true
    },
    dispatcher: {
        path: '/modules/dispatcher',
        published: true
    },
    cms: {
        path: '/modules/cms',
        published: true
    },
    auth: {
        path: '/modules/auth',
        published: true
    }
};

/**
 * Get published modules
 * Returns array of module entries
 */
export function getPublishedModules(): [string, ModuleConfig][] {
    return Object.entries(modulesConfig)
        .filter(([_, config]) => config.published);
}
