// This file is auto-generated by scripts/generate-auto-menus.ts
// Do not edit this file directly.

export const autoNavigationItems = [
  {
    id: 'docs',
    title: 'Documentation',
    icon: 'ri:book-line',
    items: [
      {
        title: 'Documentation',
        path: '/docs/home',
        icon: 'ri:list-unordered'
      }
    ]
  }
];
