// This file is auto-generated by scripts/generate-auto-menus.ts
// Do not edit this file directly.

export const autoNavigationItems = [
  {
    title: 'Demo',
    isOpen: true,
    items: [
      {
        title: 'Layouts',
        isOpen: true,
        icon: 'ri:layout-line',
        items: [
          {
            title: 'Grid',
            path: '/demo/layout/grid',
            icon: 'ri:layout-grid-line'
          },
          {
            title: 'Flex',
            path: '/demo/layout/flex',
            icon: 'ri:layout-row-line'
          },
          {
            title: 'Stack',
            path: '/demo/layout/stack',
            icon: 'ri:stack-line'
          }
        ]
      },
      {
        title: 'System',
        isOpen: true,
        icon: 'ri:settings-3-line',
        items: [
          {
            title: 'Login',
            path: '/demo/system/login',
            icon: 'ri:login-box-line'
          },
          {
            title: 'Register',
            path: '/demo/system/register',
            icon: 'ri:user-add-line'
          },
          {
            title: 'Register Simple',
            path: '/demo/system/register-simple',
            icon: 'ri:user-add-line'
          },
          {
            title: 'Set Password',
            path: '/demo/system/set-password',
            icon: 'ri:lock-password-line'
          },
          {
            title: 'Forgot Password',
            path: '/demo/system/forgot-password',
            icon: 'ri:key-line'
          },
          {
            title: 'Setup 2FA',
            path: '/demo/system/setup-2fa',
            icon: 'ri:shield-keyhole-line'
          },
          {
            title: 'Verify Code',
            path: '/demo/system/verify-code',
            icon: 'ri:checkbox-circle-line'
          },
          {
            title: 'Verify Email',
            path: '/demo/system/verify-email',
            icon: 'ri:mail-check-line'
          },
          {
            title: 'Access denied',
            path: '/demo/system/access-denied',
            icon: 'ri:error-warning-line'
          },
          {
            title: '404',
            path: '/demo/system/404',
            icon: 'ri:compass-3-line'
          },
          {
            title: 'Error',
            path: '/demo/system/error',
            icon: 'ri:bug-line'
          }
        ]
      },
      {
        title: 'Dashboard',
        path: '/demo/dashboard',
        icon: 'ri:dashboard-3-line'
      },
      {
        title: 'Blog Post',
        path: '/demo/blog-post',
        icon: 'ri:newspaper-line'
      },
      {
        title: 'Form',
        path: '/demo/form',
        icon: 'ri:file-list-3-line'
      },
      {
        title: 'Modals',
        path: '/demo/modals',
        icon: 'ri:window-2-line'
      },
      {
        title: 'Tables',
        path: '/demo/tables',
        icon: 'ri:table-alt-line'
      },
      {
        title: 'Buttons',
        path: '/demo/buttons',
        icon: 'ri:radio-button-line'
      },
      {
        title: 'Inputs',
        path: '/demo/inputs',
        icon: 'ri:input-method-line'
      },
      {
        title: 'Selects',
        path: '/demo/selects',
        icon: 'ri:dropdown-list'
      },
      {
        title: 'Cards',
        path: '/demo/cards',
        icon: 'ri:id-card-line'
      },
      {
        title: 'Events',
        path: '/demo/events',
        icon: 'ri:calendar-event-line'
      },
      {
        title: 'User Management',
        icon: 'ri:group-line',
        isOpen: true,
        items: [
          {
            title: 'Dashboard',
            path: '/demo/users/dashboard',
            icon: 'ri:dashboard-3-line'
          },
          {
            title: 'Active Sessions',
            path: '/demo/users/sessions',
            icon: 'ri:time-line'
          },
          {
            title: 'Login History',
            path: '/demo/users/login-history',
            icon: 'ri:history-line'
          }
        ]
      }
    ]
  }
];
