// This file is auto-generated by scripts/generate-auto-menus.ts
// Do not edit this file directly.

export const autoNavigationItems = [
  {
    title: 'General',
    isOpen: true,
    items: [
      {
        title: 'Dashboard',
        path: '/dashboard',
        icon: 'ri:dashboard-line'
      },
      {
        id: 'web-analytics',
        title: 'Analytics',
        icon: 'ri:line-chart-line',
        isOpen: true,
        items: [
          {
            title: 'Dashboard',
            path: '/web-analytics/dashboard',
            icon: 'ri:dashboard-line'
          }
        ]
      },
      {
        id: 'cms',
        title: 'Content',
        icon: 'ri:file-text-line',
        isOpen: true,
        ability: {
          action: 'manage',
          subject: 'cms'
        },
        items: [
          {
            title: 'Dashboard',
            path: '/cms/dashboard',
            icon: 'ri:dashboard-line'
          },
          {
            title: 'Content Management',
            path: '/cms/content',
            icon: 'ri:list-unordered'
          }
        ]
      },
      {
        id: 'crm',
        title: 'CRM',
        icon: 'ri:contacts-line',
        isOpen: true,
        ability: {
          action: 'manage',
          subject: 'all'
        },
        items: [
          {
            title: 'Contacts',
            path: '/crm/contacts',
            icon: 'ri:user-line'
          },
          {
            title: 'Messages',
            path: '/crm/messages',
            icon: 'ri:message-line'
          }
        ]
      },
      {
        id: 'project_management',
        title: 'Project Management',
        icon: 'ri:folder-line',
        isOpen: true,
        ability: {
          action: 'read',
          subject: 'project-management'
        },
        items: [
          {
            title: 'All Projects',
            path: '/project-management/projects',
            icon: 'ri:folder-line'
          },
          {
            title: 'Workspace',
            path: '/project-management/workspace',
            icon: 'ri:layout-grid-line'
          },
          {
            title: 'My Tasks',
            path: '/project-management/my-tasks',
            icon: 'ri:checkbox-line'
          }
        ]
      },
      {
        id: 'file-manager',
        title: 'File Manager',
        icon: 'ri-file-cloud-line',
        isOpen: true,
        ability: {
          action: 'manage',
          subject: 'all'
        },
        items: [
          {
            title: 'All Files',
            path: '/file-manager',
            icon: 'ri-file-list-line'
          }
        ]
      },
      {
        id: 'users_auth',
        title: 'User Management',
        icon: 'ri:group-line',
        isOpen: true,
        ability: {
          action: 'manage',
          subject: 'user'
        },
        items: [
          {
            title: 'Dashboard',
            path: '/user-management/dashboard',
            icon: 'ri:dashboard-3-line'
          },
          {
            title: 'User List',
            path: '/user-management/users/list',
            icon: 'ri:user-line'
          },
          {
            title: 'Active Sessions',
            path: '/user-management/sessions',
            icon: 'ri:time-line'
          },
          {
            title: 'Login History',
            path: '/user-management/login-history',
            icon: 'ri:history-line'
          },
          {
            title: 'Role List',
            path: '/user-management/roles/list',
            icon: 'ri:shield-line',
            ability: {
              action: 'manage',
              subject: 'role'
            }
          }
        ]
      },
      {
        id: 'newsletter_management',
        title: 'Newsletter',
        icon: 'ri:mail-line',
        isOpen: true,
        ability: {
          action: 'manage',
          subject: 'user'
        },
        items: [
          {
            title: 'Dashboard',
            path: '/newsletter/dashboard',
            icon: 'ri:dashboard-3-line'
          },
          {
            title: 'Manage Subscribers',
            path: '/newsletter/subscriptions',
            icon: 'ri:user-received-line'
          },
          {
            title: 'Email Templates',
            path: '/newsletter/templates',
            icon: 'ri:file-text-line'
          },
          {
            title: 'Campaigns',
            path: '/newsletter/campaigns',
            icon: 'ri:send-plane-line'
          }
        ]
      },
      {
        id: 'waitlist_management',
        title: 'Waitlist',
        icon: 'ri:list-check-2',
        isOpen: false,
        ability: {
          action: 'manage',
          subject: 'user'
        },
        items: [
          {
            title: 'Dashboard',
            path: '/waitlist/dashboard',
            icon: 'ri:dashboard-3-line'
          },
          {
            title: 'All Signups',
            path: '/waitlist/signups-list',
            icon: 'ri:user-received-2-line'
          }
        ]
      },
      {
        id: 'social_media',
        title: 'Social Media',
        icon: 'ri:share-line',
        isOpen: true,
        ability: {
          action: 'manage',
          subject: 'all'
        },
        items: [
          {
            title: 'Planner',
            path: '/social-media/planner',
            icon: 'ri:calendar-schedule-line'
          }
        ]
      },
      {
        id: 'image_lab',
        title: 'Image Lab',
        icon: 'ri:image-ai-line',
        isOpen: true,
        ability: {
          action: 'manage',
          subject: 'all'
        },
        items: [
          {
            title: 'AI Studio',
            path: '/image-lab',
            icon: 'ri:palette-line'
          }
        ]
      },
      {
        id: 'photoshoot',
        title: 'AI Photoshoot',
        icon: 'ri:camera-ai-line',
        isOpen: true,
        ability: {
          action: 'manage',
          subject: 'all'
        },
        items: [
          {
            title: 'Sessions',
            path: '/photoshoot/sessions',
            icon: 'ri:gallery-line'
          }
        ]
      }
    ]
  },
  {
    id: 'workflow',
    title: 'Workflow',
    icon: 'ri:flow-chart',
    isOpen: true,
    items: [
      {
        title: 'Workflows',
        path: '/workflow/list',
        icon: 'ri:list-check'
      },
      {
        title: 'Builder',
        path: '/workflow/builder',
        icon: 'ri:palette-line'
      },
      {
        title: 'Executions',
        path: '/workflow/executions',
        icon: 'ri:history-line'
      },
      {
        title: 'Tester',
        path: '/workflow/tester',
        icon: 'ri:test-tube-line'
      }
    ]
  },
  {
    id: 'demo-ui',
    title: 'UI Library',
    icon: 'ri:palette-line',
    isOpen: false,
    ability: {
      action: 'manage',
      subject: 'all'
    },
    items: [
      {
        title: 'Components',
        icon: 'ri:shapes-line',
        isOpen: false,
        items: [
          {
            title: 'Buttons',
            path: '/demo-ui/components/buttons',
            icon: 'ri:radio-button-line'
          },
          {
            title: 'Inputs',
            path: '/demo-ui/components/inputs',
            icon: 'ri:input-method-line'
          },
          {
            title: 'Selects',
            path: '/demo-ui/components/selects',
            icon: 'ri:dropdown-list'
          },
          {
            title: 'Cards',
            path: '/demo-ui/components/cards',
            icon: 'ri:id-card-line'
          },
          {
            title: 'Tables',
            path: '/demo-ui/components/tables',
            icon: 'ri:table-alt-line'
          },
          {
            title: 'Modals',
            path: '/demo-ui/components/modals',
            icon: 'ri:window-2-line'
          },
          {
            title: 'Form',
            path: '/demo-ui/components/form',
            icon: 'ri:file-list-3-line'
          },
          {
            title: 'Events',
            path: '/demo-ui/components/events',
            icon: 'ri:calendar-event-line'
          },
          {
            title: 'Fonts',
            path: '/demo-ui/components/fonts',
            icon: 'ri:font-size'
          },
          {
            title: 'Icons',
            path: '/demo-ui/components/icons',
            icon: 'ri:remixicon-line'
          },
          {
            title: 'Spinner',
            path: '/demo-ui/components/spinner',
            icon: 'ri:loader-4-line'
          }
        ]
      },
      {
        title: 'Layouts',
        icon: 'ri:layout-line',
        isOpen: false,
        items: [
          {
            title: 'Grid',
            path: '/demo-ui/layouts/grid',
            icon: 'ri:layout-grid-line'
          },
          {
            title: 'Flex',
            path: '/demo-ui/layouts/flex',
            icon: 'ri:layout-row-line'
          },
          {
            title: 'Stack',
            path: '/demo-ui/layouts/stack',
            icon: 'ri:stack-line'
          }
        ]
      },
      {
        title: 'Page Templates',
        icon: 'ri:file-copy-line',
        isOpen: false,
        items: [
          {
            title: 'Login',
            path: '/demo-ui/templates/login',
            icon: 'ri:login-box-line'
          },
          {
            title: 'Register',
            path: '/demo-ui/templates/register',
            icon: 'ri:user-add-line'
          },
          {
            title: 'Forgot Password',
            path: '/demo-ui/templates/forgot-password',
            icon: 'ri:key-line'
          },
          {
            title: 'Set Password',
            path: '/demo-ui/templates/set-password',
            icon: 'ri:lock-password-line'
          },
          {
            title: 'Verify Email',
            path: '/demo-ui/templates/verify-email',
            icon: 'ri:mail-check-line'
          },
          {
            title: '2FA Setup',
            path: '/demo-ui/templates/setup-2fa',
            icon: 'ri:shield-keyhole-line'
          },
          {
            title: '404 Page',
            path: '/demo-ui/templates/404',
            icon: 'ri:compass-3-line'
          },
          {
            title: 'Error Page',
            path: '/demo-ui/templates/error',
            icon: 'ri:bug-line'
          },
          {
            title: 'Access Denied',
            path: '/demo-ui/templates/access-denied',
            icon: 'ri:error-warning-line'
          }
        ]
      },
      {
        title: 'Content',
        icon: 'ri:article-line',
        isOpen: false,
        items: [
          {
            title: 'Blog Post',
            path: '/demo-ui/content/blog-post',
            icon: 'ri:newspaper-line'
          }
        ]
      }
    ]
  },
  {
    id: 'compass',
    title: 'Compass',
    icon: 'ri:compass-3-line',
    isOpen: true,
    items: [
      {
        title: 'Dashboard',
        path: '/compass/dashboard',
        icon: 'ri:dashboard-line'
      },
      {
        title: 'Tree View',
        path: '/compass/tree-canvas',
        icon: 'ri:node-tree'
      },
      {
        title: 'Timeline View',
        path: '/compass/timeline',
        icon: 'ri:calendar-line'
      }
    ]
  },
  {
    id: 'ai-agent',
    title: 'AI Agent',
    icon: 'ri:robot-line',
    isOpen: true,
    items: [
      {
        title: 'Chat',
        path: '/ai-agent',
        icon: 'ri:chat-ai-line'
      },
      {
        title: 'Logs',
        path: '/ai-agent/logs',
        icon: 'ri:file-list-3-line'
      }
    ]
  },
  {
    id: 'system_management',
    title: 'System',
    icon: 'ri:settings-3-line',
    isOpen: true,
    ability: {
      action: 'manage',
      subject: 'user'
    },
    items: [
      {
        title: 'Dashboard',
        path: '/system/dashboard',
        icon: 'ri:dashboard-3-line'
      },
      {
        title: 'Settings',
        path: '/system/settings',
        icon: 'ri:settings-4-line'
      },
      {
        title: 'Theme Editor',
        path: '/system/theme-editor',
        icon: 'ri:palette-line'
      },
      {
        title: 'Routes',
        path: '/routes',
        icon: 'ri:route-line'
      },
      {
        title: 'Logs',
        path: '/system/logs',
        icon: 'ri:file-list-3-line'
      }
    ]
  },
  {
    id: 'dispatcher',
    title: 'Dispatcher',
    icon: 'ri:send-plane-line',
    isOpen: true,
    ability: {
      action: 'manage',
      subject: 'task'
    },
    items: [
      {
        title: 'Tasks',
        path: '/dispatcher/tasks',
        icon: 'ri:task-line'
      },
      {
        title: 'Queues',
        path: '/dispatcher/queues',
        icon: 'ri:stack-line'
      }
    ]
  },
  {
    id: 'payments_management',
    title: 'Billing',
    icon: 'ri:wallet-3-line',
    isOpen: false,
    ability: {
      action: 'manage',
      subject: 'user'
    },
    items: [
      {
        title: 'Upgrade',
        path: '/payments/upgrade',
        icon: 'ri:vip-crown-line'
      },
      {
        title: 'Subscription',
        path: '/payments/subscription',
        icon: 'ri:user-settings-line'
      },
      {
        title: 'Token Balance',
        path: '/payments/tokens',
        icon: 'ri:coin-line'
      },
      {
        title: 'Usage & Quotas',
        path: '/payments/usage',
        icon: 'ri:bar-chart-box-line'
      },
      {
        title: 'Payment Config',
        path: '/payments/admin/config',
        icon: 'ri:settings-3-line',
        ability: {
          action: 'manage',
          subject: 'admin'
        }
      },
      {
        title: 'Quota Management',
        path: '/payments/admin/quotas',
        icon: 'ri:dashboard-line',
        ability: {
          action: 'manage',
          subject: 'admin'
        }
      }
    ]
  }
];
