/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<
      'index',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ai-agent': RouteRecordInfo<
      'ai-agent',
      '/ai-agent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ai-agent-logs': RouteRecordInfo<
      'ai-agent-logs',
      '/ai-agent/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'compass-dashboard': RouteRecordInfo<
      'compass-dashboard',
      '/compass/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'compass-feed': RouteRecordInfo<
      'compass-feed',
      '/compass/feed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'compass-list': RouteRecordInfo<
      'compass-list',
      '/compass/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'compass-timeline': RouteRecordInfo<
      'compass-timeline',
      '/compass/timeline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'compass-tree': RouteRecordInfo<
      'compass-tree',
      '/compass/tree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'compass-tree-canvas': RouteRecordInfo<
      'compass-tree-canvas',
      '/compass/tree-canvas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'crm-contacts-list': RouteRecordInfo<
      'crm-contacts-list',
      '/crm/contacts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'crm-contacts-edit': RouteRecordInfo<
      'crm-contacts-edit',
      '/crm/contacts/edit/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'crm-messages-list': RouteRecordInfo<
      'crm-messages-list',
      '/crm/messages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'crm-messages-edit': RouteRecordInfo<
      'crm-messages-edit',
      '/crm/messages/edit/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'getting-started': RouteRecordInfo<
      'getting-started',
      '/getting-started',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'image-lab': RouteRecordInfo<
      'image-lab',
      '/image-lab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'newsletter-campaigns': RouteRecordInfo<
      'newsletter-campaigns',
      '/newsletter/campaigns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'newsletter-campaign-detail': RouteRecordInfo<
      'newsletter-campaign-detail',
      '/newsletter/campaigns/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'newsletter-dashboard': RouteRecordInfo<
      'newsletter-dashboard',
      '/newsletter/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'newsletter-subscriptions': RouteRecordInfo<
      'newsletter-subscriptions',
      '/newsletter/subscriptions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'newsletter-templates': RouteRecordInfo<
      'newsletter-templates',
      '/newsletter/templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'newsletter-unsubscribe': RouteRecordInfo<
      'newsletter-unsubscribe',
      '/newsletter/unsubscribe/:token?',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'payments-subscription': RouteRecordInfo<
      'payments-subscription',
      '/payments/subscription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'payments-tokens': RouteRecordInfo<
      'payments-tokens',
      '/payments/tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'payments-upgrade': RouteRecordInfo<
      'payments-upgrade',
      '/payments/upgrade',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'payments-usage': RouteRecordInfo<
      'payments-usage',
      '/payments/usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'photoshoot-sessions': RouteRecordInfo<
      'photoshoot-sessions',
      '/photoshoot/sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'photoshoot-session-detail': RouteRecordInfo<
      'photoshoot-session-detail',
      '/photoshoot/sessions/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'my-tasks': RouteRecordInfo<
      'my-tasks',
      '/project-management/my-tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'project-management-projects': RouteRecordInfo<
      'project-management-projects',
      '/project-management/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'project-management-workspace': RouteRecordInfo<
      'project-management-workspace',
      '/project-management/workspace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'social-media-accounts': RouteRecordInfo<
      'social-media-accounts',
      '/social-media/accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'social-media-planner': RouteRecordInfo<
      'social-media-planner',
      '/social-media/planner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'waitlist-index': RouteRecordInfo<
      'waitlist-index',
      '/waitlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'waitlist-dashboard': RouteRecordInfo<
      'waitlist-dashboard',
      '/waitlist/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'waitlist-signups-list': RouteRecordInfo<
      'waitlist-signups-list',
      '/waitlist/signups-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'waitlist-thank-you': RouteRecordInfo<
      'waitlist-thank-you',
      '/waitlist/thank-you',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'waitlist-verify': RouteRecordInfo<
      'waitlist-verify',
      '/waitlist/verify/:token',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'web-analytics-dashboard': RouteRecordInfo<
      'web-analytics-dashboard',
      '/web-analytics/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'workflow-builder': RouteRecordInfo<
      'workflow-builder',
      '/workflow/builder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'workflow-executions': RouteRecordInfo<
      'workflow-executions',
      '/workflow/executions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'workflows-list': RouteRecordInfo<
      'workflows-list',
      '/workflow/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'workflow-tester': RouteRecordInfo<
      'workflow-tester',
      '/workflow/tester',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'payments-admin-config': RouteRecordInfo<
      'payments-admin-config',
      '/payments/admin/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'payments-admin-quotas-list': RouteRecordInfo<
      'payments-admin-quotas-list',
      '/payments/admin/quotas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'payments-admin-quotas-user-detail': RouteRecordInfo<
      'payments-admin-quotas-user-detail',
      '/payments/admin/quotas/user/:userId',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'forgot-password': RouteRecordInfo<
      'forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-auth-google-callback': RouteRecordInfo<
      'root-auth-google-callback',
      '/auth/google/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'register': RouteRecordInfo<
      'register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'register-simple': RouteRecordInfo<
      'register-simple',
      '/auth/register-simple',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'set-password-form': RouteRecordInfo<
      'set-password-form',
      '/auth/set-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'setup-2fa': RouteRecordInfo<
      'setup-2fa',
      '/auth/setup-2fa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-auth-twitter-callback': RouteRecordInfo<
      'root-auth-twitter-callback',
      '/auth/twitter/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'verify-code': RouteRecordInfo<
      'verify-code',
      '/auth/verify-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'verify-email': RouteRecordInfo<
      'verify-email',
      '/auth/verify-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'cms-content': RouteRecordInfo<
      'cms-content',
      '/cms/content',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'cms-dashboard': RouteRecordInfo<
      'cms-dashboard',
      '/cms/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'cms-editor': RouteRecordInfo<
      'cms-editor',
      '/cms/editor/:id?',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'cms-view': RouteRecordInfo<
      'cms-view',
      '/cms/view/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-buttons': RouteRecordInfo<
      'demo-ui-components-buttons',
      '/demo-ui/components/buttons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-cards': RouteRecordInfo<
      'demo-ui-components-cards',
      '/demo-ui/components/cards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-events': RouteRecordInfo<
      'demo-ui-components-events',
      '/demo-ui/components/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-fonts': RouteRecordInfo<
      'demo-ui-components-fonts',
      '/demo-ui/components/fonts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-form': RouteRecordInfo<
      'demo-ui-components-form',
      '/demo-ui/components/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-icons': RouteRecordInfo<
      'demo-ui-components-icons',
      '/demo-ui/components/icons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-inputs': RouteRecordInfo<
      'demo-ui-components-inputs',
      '/demo-ui/components/inputs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-modals': RouteRecordInfo<
      'demo-ui-components-modals',
      '/demo-ui/components/modals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-selects': RouteRecordInfo<
      'demo-ui-components-selects',
      '/demo-ui/components/selects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-spinner': RouteRecordInfo<
      'demo-ui-components-spinner',
      '/demo-ui/components/spinner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-components-tables': RouteRecordInfo<
      'demo-ui-components-tables',
      '/demo-ui/components/tables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-components-features-table': RouteRecordInfo<
      'root-components-features-table',
      '/components/FeaturesTable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-components-features-table+icons': RouteRecordInfo<
      'root-components-features-table+icons',
      '/components/FeaturesTable+icons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-components-how-it-works': RouteRecordInfo<
      'root-components-how-it-works',
      '/components/HowItWorks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-components-newsletter-subscription-modal': RouteRecordInfo<
      'root-components-newsletter-subscription-modal',
      '/components/NewsletterSubscriptionModal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-content-blog-post': RouteRecordInfo<
      'demo-ui-content-blog-post',
      '/demo-ui/content/blog-post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dispatcher-task-history-detail': RouteRecordInfo<
      'dispatcher-task-history-detail',
      '/dispatcher/history/view/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dispatcher-queues': RouteRecordInfo<
      'dispatcher-queues',
      '/dispatcher/queues',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-priority-icon': RouteRecordInfo<
      'root-dispatcher-queues-components-priority-icon',
      '/dispatcher/queues/components/PriorityIcon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-queues-manager': RouteRecordInfo<
      'root-dispatcher-queues-components-queues-manager',
      '/dispatcher/queues/components/QueuesManager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-queues-sidebar': RouteRecordInfo<
      'root-dispatcher-queues-components-queues-sidebar',
      '/dispatcher/queues/components/QueuesSidebar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-task-creator': RouteRecordInfo<
      'root-dispatcher-queues-components-task-creator',
      '/dispatcher/queues/components/TaskCreator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-task-creator-content': RouteRecordInfo<
      'root-dispatcher-queues-components-task-creator-content',
      '/dispatcher/queues/components/TaskCreatorContent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-task-detail-content': RouteRecordInfo<
      'root-dispatcher-queues-components-task-detail-content',
      '/dispatcher/queues/components/TaskDetailContent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-task-history-detail-content': RouteRecordInfo<
      'root-dispatcher-queues-components-task-history-detail-content',
      '/dispatcher/queues/components/TaskHistoryDetailContent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-task-history-list': RouteRecordInfo<
      'root-dispatcher-queues-components-task-history-list',
      '/dispatcher/queues/components/TaskHistoryList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-tasks-grid': RouteRecordInfo<
      'root-dispatcher-queues-components-tasks-grid',
      '/dispatcher/queues/components/TasksGrid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'root-dispatcher-queues-components-tasks-main': RouteRecordInfo<
      'root-dispatcher-queues-components-tasks-main',
      '/dispatcher/queues/components/TasksMain',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dispatcher-tasks': RouteRecordInfo<
      'dispatcher-tasks',
      '/dispatcher/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dispatcher-tasks-create': RouteRecordInfo<
      'dispatcher-tasks-create',
      '/dispatcher/tasks/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dispatcher-task-edit': RouteRecordInfo<
      'dispatcher-task-edit',
      '/dispatcher/tasks/edit/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dispatcher-tasks-view': RouteRecordInfo<
      'dispatcher-tasks-view',
      '/dispatcher/tasks/view/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'file-manager': RouteRecordInfo<
      'file-manager',
      '/file-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-flex': RouteRecordInfo<
      'demo-flex',
      '/demo-ui/layouts/flex',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'grid-layout-demo': RouteRecordInfo<
      'grid-layout-demo',
      '/demo-ui/layouts/grid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'stack-layout-demo': RouteRecordInfo<
      'stack-layout-demo',
      '/demo-ui/layouts/stack',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'profile': RouteRecordInfo<
      'profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'project-view': RouteRecordInfo<
      'project-view',
      '/project-management/project/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'project-create': RouteRecordInfo<
      'project-create',
      '/project-management/projects/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'project-edit': RouteRecordInfo<
      'project-edit',
      '/project-management/projects/edit/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'route-management': RouteRecordInfo<
      'route-management',
      '/routes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'route-create': RouteRecordInfo<
      'route-create',
      '/routes/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'route-edit': RouteRecordInfo<
      'route-edit',
      '/routes/edit/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'system-dashboard': RouteRecordInfo<
      'system-dashboard',
      '/system/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'system-logs': RouteRecordInfo<
      'system-logs',
      '/system/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'system-settings': RouteRecordInfo<
      'system-settings',
      '/system/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'theme-editor': RouteRecordInfo<
      'theme-editor',
      '/system/theme-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'task-create': RouteRecordInfo<
      'task-create',
      '/project-management/project/:projectId/task/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'task-edit': RouteRecordInfo<
      'task-edit',
      '/project-management/project/:projectId/task/edit/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-404': RouteRecordInfo<
      'demo-404',
      '/demo-ui/templates/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-access-denied': RouteRecordInfo<
      'demo-access-denied',
      '/demo-ui/templates/access-denied',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-ui-templates-error': RouteRecordInfo<
      'demo-ui-templates-error',
      '/demo-ui/templates/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-forgot-password': RouteRecordInfo<
      'demo-forgot-password',
      '/demo-ui/templates/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-login-form': RouteRecordInfo<
      'demo-login-form',
      '/demo-ui/templates/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-register-form': RouteRecordInfo<
      'demo-register-form',
      '/demo-ui/templates/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-set-password-form': RouteRecordInfo<
      'demo-set-password-form',
      '/demo-ui/templates/set-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-setup-2fa-form': RouteRecordInfo<
      'demo-setup-2fa-form',
      '/demo-ui/templates/setup-2fa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo-verify-email-form': RouteRecordInfo<
      'demo-verify-email-form',
      '/demo-ui/templates/verify-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user-management-dashboard': RouteRecordInfo<
      'user-management-dashboard',
      '/user-management/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login-history': RouteRecordInfo<
      'login-history',
      '/user-management/login-history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'active-sessions': RouteRecordInfo<
      'active-sessions',
      '/user-management/sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'create-role': RouteRecordInfo<
      'create-role',
      '/user-management/roles/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'edit-role': RouteRecordInfo<
      'edit-role',
      '/user-management/roles/edit/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'roles-list': RouteRecordInfo<
      'roles-list',
      '/user-management/roles/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'create-user': RouteRecordInfo<
      'create-user',
      '/user-management/users/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'users-edit': RouteRecordInfo<
      'users-edit',
      '/user-management/users/edit/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'users-list': RouteRecordInfo<
      'users-list',
      '/user-management/users/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/home.vue': {
      routes:
        | 'index'
      views:
        | never
    }
    '../../plugins/ai-agent/frontend/pages/ai-agent.vue': {
      routes:
        | 'ai-agent'
      views:
        | never
    }
    '../../plugins/ai-agent/frontend/pages/ai-agent-logs.vue': {
      routes:
        | 'ai-agent-logs'
      views:
        | never
    }
    '../../plugins/compass/frontend/pages/compass-dashboard.vue': {
      routes:
        | 'compass-dashboard'
      views:
        | never
    }
    '../../plugins/compass/frontend/pages/compass-feed.vue': {
      routes:
        | 'compass-feed'
      views:
        | never
    }
    '../../plugins/compass/frontend/pages/compass-list.vue': {
      routes:
        | 'compass-list'
      views:
        | never
    }
    '../../plugins/compass/frontend/pages/compass-timeline.vue': {
      routes:
        | 'compass-timeline'
      views:
        | never
    }
    '../../plugins/compass/frontend/pages/compass-tree.vue': {
      routes:
        | 'compass-tree'
      views:
        | never
    }
    '../../plugins/compass/frontend/pages/compass-tree-canvas.vue': {
      routes:
        | 'compass-tree-canvas'
      views:
        | never
    }
    '../../plugins/crm/frontend/pages/contacts-list.vue': {
      routes:
        | 'crm-contacts-list'
      views:
        | never
    }
    '../../plugins/crm/frontend/pages/contact-edit.vue': {
      routes:
        | 'crm-contacts-edit'
      views:
        | never
    }
    '../../plugins/crm/frontend/pages/messages-list.vue': {
      routes:
        | 'crm-messages-list'
      views:
        | never
    }
    '../../plugins/crm/frontend/pages/message-edit.vue': {
      routes:
        | 'crm-messages-edit'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | 'dashboard'
      views:
        | never
    }
    'src/pages/getting-started.vue': {
      routes:
        | 'getting-started'
      views:
        | never
    }
    '../../plugins/image-lab/frontend/pages/image-lab.vue': {
      routes:
        | 'image-lab'
      views:
        | never
    }
    '../../plugins/newsletter/frontend/pages/newsletter-campaigns.vue': {
      routes:
        | 'newsletter-campaigns'
      views:
        | never
    }
    '../../plugins/newsletter/frontend/pages/newsletter-campaign-detail.vue': {
      routes:
        | 'newsletter-campaign-detail'
      views:
        | never
    }
    '../../plugins/newsletter/frontend/pages/newsletter-dashboard.vue': {
      routes:
        | 'newsletter-dashboard'
      views:
        | never
    }
    '../../plugins/newsletter/frontend/pages/newsletter-subscriptions.vue': {
      routes:
        | 'newsletter-subscriptions'
      views:
        | never
    }
    '../../plugins/newsletter/frontend/pages/newsletter-templates.vue': {
      routes:
        | 'newsletter-templates'
      views:
        | never
    }
    '../../plugins/newsletter/frontend/pages/newsletter-unsubscribe.vue': {
      routes:
        | 'newsletter-unsubscribe'
      views:
        | never
    }
    '../../plugins/payments/frontend/pages/subscription.vue': {
      routes:
        | 'payments-subscription'
      views:
        | never
    }
    '../../plugins/payments/frontend/pages/tokens.vue': {
      routes:
        | 'payments-tokens'
      views:
        | never
    }
    '../../plugins/payments/frontend/pages/upgrade.vue': {
      routes:
        | 'payments-upgrade'
      views:
        | never
    }
    '../../plugins/payments/frontend/pages/usage.vue': {
      routes:
        | 'payments-usage'
      views:
        | never
    }
    '../../plugins/photoshoot/frontend/pages/photoshoot-sessions.vue': {
      routes:
        | 'photoshoot-sessions'
      views:
        | never
    }
    '../../plugins/photoshoot/frontend/pages/photoshoot-session-detail.vue': {
      routes:
        | 'photoshoot-session-detail'
      views:
        | never
    }
    '../../plugins/project-management/frontend/pages/my-tasks.vue': {
      routes:
        | 'my-tasks'
      views:
        | never
    }
    '../../plugins/project-management/frontend/pages/projects.vue': {
      routes:
        | 'project-management-projects'
      views:
        | never
    }
    '../../plugins/project-management/frontend/pages/projects-workspace.vue': {
      routes:
        | 'project-management-workspace'
      views:
        | never
    }
    '../../plugins/social-media/frontend/pages/accounts-layout.vue': {
      routes:
        | 'social-media-accounts'
      views:
        | never
    }
    '../../plugins/social-media/frontend/pages/social-media-planner.vue': {
      routes:
        | 'social-media-planner'
      views:
        | never
    }
    '../../plugins/waitlist/frontend/pages/waitlist.vue': {
      routes:
        | 'waitlist-index'
      views:
        | never
    }
    '../../plugins/waitlist/frontend/pages/waitlist-dashboard.vue': {
      routes:
        | 'waitlist-dashboard'
      views:
        | never
    }
    '../../plugins/waitlist/frontend/pages/signups-list.vue': {
      routes:
        | 'waitlist-signups-list'
      views:
        | never
    }
    '../../plugins/waitlist/frontend/pages/thank-you.vue': {
      routes:
        | 'waitlist-thank-you'
      views:
        | never
    }
    '../../plugins/waitlist/frontend/pages/verify.vue': {
      routes:
        | 'waitlist-verify'
      views:
        | never
    }
    '../../plugins/web-analytics/frontend/pages/web-analytics-dashboard.vue': {
      routes:
        | 'web-analytics-dashboard'
      views:
        | never
    }
    '../../plugins/workflow/frontend/pages/workflow-builder.vue': {
      routes:
        | 'workflow-builder'
      views:
        | never
    }
    '../../plugins/workflow/frontend/pages/workflow-executions.vue': {
      routes:
        | 'workflow-executions'
      views:
        | never
    }
    '../../plugins/workflow/frontend/pages/workflows-list.vue': {
      routes:
        | 'workflows-list'
      views:
        | never
    }
    '../../plugins/workflow/frontend/pages/workflow-tester.vue': {
      routes:
        | 'workflow-tester'
      views:
        | never
    }
    '../../plugins/payments/frontend/pages/admin/payment-config.vue': {
      routes:
        | 'payments-admin-config'
      views:
        | never
    }
    '../../plugins/payments/frontend/pages/admin/quotas.list.vue': {
      routes:
        | 'payments-admin-quotas-list'
      views:
        | never
    }
    '../../plugins/payments/frontend/pages/admin/quotas.user-detail.vue': {
      routes:
        | 'payments-admin-quotas-user-detail'
      views:
        | never
    }
    'src/modules/auth/pages/forgot-password.vue': {
      routes:
        | 'forgot-password'
      views:
        | never
    }
    'src/modules/auth/pages/google/callback.vue': {
      routes:
        | 'root-auth-google-callback'
      views:
        | never
    }
    'src/modules/auth/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/modules/auth/pages/register.vue': {
      routes:
        | 'register'
      views:
        | never
    }
    'src/modules/auth/pages/register-simple.vue': {
      routes:
        | 'register-simple'
      views:
        | never
    }
    'src/modules/auth/pages/set-password.vue': {
      routes:
        | 'set-password-form'
      views:
        | never
    }
    'src/modules/auth/pages/setup-2fa.vue': {
      routes:
        | 'setup-2fa'
      views:
        | never
    }
    'src/pages/auth/twitter/callback.vue': {
      routes:
        | 'root-auth-twitter-callback'
      views:
        | never
    }
    'src/modules/auth/pages/verify-code.vue': {
      routes:
        | 'verify-code'
      views:
        | never
    }
    'src/modules/auth/pages/verify-email.vue': {
      routes:
        | 'verify-email'
      views:
        | never
    }
    'src/modules/cms/pages/cms-list.vue': {
      routes:
        | 'cms-content'
      views:
        | never
    }
    'src/modules/cms/pages/cms-dashboard.vue': {
      routes:
        | 'cms-dashboard'
      views:
        | never
    }
    'src/modules/cms/pages/cms-editor.vue': {
      routes:
        | 'cms-editor'
      views:
        | never
    }
    'src/modules/cms/pages/cms-view.vue': {
      routes:
        | 'cms-view'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/buttons.vue': {
      routes:
        | 'demo-ui-components-buttons'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/cards.vue': {
      routes:
        | 'demo-ui-components-cards'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/events.vue': {
      routes:
        | 'demo-ui-components-events'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/fonts.vue': {
      routes:
        | 'demo-ui-components-fonts'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/form.vue': {
      routes:
        | 'demo-ui-components-form'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/icons.vue': {
      routes:
        | 'demo-ui-components-icons'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/inputs.vue': {
      routes:
        | 'demo-ui-components-inputs'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/modals.vue': {
      routes:
        | 'demo-ui-components-modals'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/selects.vue': {
      routes:
        | 'demo-ui-components-selects'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/spinner.vue': {
      routes:
        | 'demo-ui-components-spinner'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/components/tables.vue': {
      routes:
        | 'demo-ui-components-tables'
      views:
        | never
    }
    'src/pages/components/FeaturesTable.vue': {
      routes:
        | 'root-components-features-table'
      views:
        | never
    }
    'src/pages/components/FeaturesTable+icons.vue': {
      routes:
        | 'root-components-features-table+icons'
      views:
        | never
    }
    'src/pages/components/HowItWorks.vue': {
      routes:
        | 'root-components-how-it-works'
      views:
        | never
    }
    'src/pages/components/NewsletterSubscriptionModal.vue': {
      routes:
        | 'root-components-newsletter-subscription-modal'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/content/blog-post.vue': {
      routes:
        | 'demo-ui-content-blog-post'
      views:
        | never
    }
    'src/modules/dispatcher/pages/history/task-history-details.vue': {
      routes:
        | 'dispatcher-task-history-detail'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/index.vue': {
      routes:
        | 'dispatcher-queues'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/PriorityIcon.vue': {
      routes:
        | 'root-dispatcher-queues-components-priority-icon'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/QueuesManager.vue': {
      routes:
        | 'root-dispatcher-queues-components-queues-manager'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/QueuesSidebar.vue': {
      routes:
        | 'root-dispatcher-queues-components-queues-sidebar'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/TaskCreator.vue': {
      routes:
        | 'root-dispatcher-queues-components-task-creator'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/TaskCreatorContent.vue': {
      routes:
        | 'root-dispatcher-queues-components-task-creator-content'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/TaskDetailContent.vue': {
      routes:
        | 'root-dispatcher-queues-components-task-detail-content'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/TaskHistoryDetailContent.vue': {
      routes:
        | 'root-dispatcher-queues-components-task-history-detail-content'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/TaskHistoryList.vue': {
      routes:
        | 'root-dispatcher-queues-components-task-history-list'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/TasksGrid.vue': {
      routes:
        | 'root-dispatcher-queues-components-tasks-grid'
      views:
        | never
    }
    'src/modules/dispatcher/pages/queues/components/TasksMain.vue': {
      routes:
        | 'root-dispatcher-queues-components-tasks-main'
      views:
        | never
    }
    'src/modules/dispatcher/pages/tasks/tasks-list.vue': {
      routes:
        | 'dispatcher-tasks'
      views:
        | never
    }
    'src/modules/dispatcher/pages/tasks/task-create.vue': {
      routes:
        | 'dispatcher-tasks-create'
      views:
        | never
    }
    'src/modules/dispatcher/pages/tasks/task-edit.vue': {
      routes:
        | 'dispatcher-task-edit'
      views:
        | never
    }
    'src/modules/dispatcher/pages/tasks/task-view.vue': {
      routes:
        | 'dispatcher-tasks-view'
      views:
        | never
    }
    'src/modules/file-manager/pages/file-manager.vue': {
      routes:
        | 'file-manager'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/layouts/flex.vue': {
      routes:
        | 'demo-flex'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/layouts/grid.vue': {
      routes:
        | 'grid-layout-demo'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/layouts/stack.vue': {
      routes:
        | 'stack-layout-demo'
      views:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | 'profile'
      views:
        | never
    }
    '../../plugins/project-management/frontend/pages/project/view.vue': {
      routes:
        | 'project-view'
      views:
        | never
    }
    '../../plugins/project-management/frontend/pages/project/create.vue': {
      routes:
        | 'project-create'
      views:
        | never
    }
    '../../plugins/project-management/frontend/pages/project/edit.vue': {
      routes:
        | 'project-edit'
      views:
        | never
    }
    'src/modules/routes/pages/routes-list.vue': {
      routes:
        | 'route-management'
      views:
        | never
    }
    'src/modules/routes/pages/route-create.vue': {
      routes:
        | 'route-create'
      views:
        | never
    }
    'src/modules/routes/pages/route-edit.vue': {
      routes:
        | 'route-edit'
      views:
        | never
    }
    'src/modules/system/pages/system-dashboard.vue': {
      routes:
        | 'system-dashboard'
      views:
        | never
    }
    'src/modules/system/pages/system-logs.vue': {
      routes:
        | 'system-logs'
      views:
        | never
    }
    'src/modules/system/pages/system-settings.vue': {
      routes:
        | 'system-settings'
      views:
        | never
    }
    'src/modules/system/pages/theme-editor/index.vue': {
      routes:
        | 'theme-editor'
      views:
        | never
    }
    '../../plugins/project-management/frontend/pages/task/create.vue': {
      routes:
        | 'task-create'
      views:
        | never
    }
    '../../plugins/project-management/frontend/pages/task/edit.vue': {
      routes:
        | 'task-edit'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/404.vue': {
      routes:
        | 'demo-404'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/access-denied.vue': {
      routes:
        | 'demo-access-denied'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/error.vue': {
      routes:
        | 'demo-ui-templates-error'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/forgot-password.vue': {
      routes:
        | 'demo-forgot-password'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/login.vue': {
      routes:
        | 'demo-login-form'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/register.vue': {
      routes:
        | 'demo-register-form'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/set-password.vue': {
      routes:
        | 'demo-set-password-form'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/setup-2fa.vue': {
      routes:
        | 'demo-setup-2fa-form'
      views:
        | never
    }
    '../../plugins/demo-ui/frontend/pages/templates/verify-email.vue': {
      routes:
        | 'demo-verify-email-form'
      views:
        | never
    }
    'src/modules/user-management/pages/dashboard.vue': {
      routes:
        | 'user-management-dashboard'
      views:
        | never
    }
    'src/modules/user-management/pages/login-history.vue': {
      routes:
        | 'login-history'
      views:
        | never
    }
    'src/modules/user-management/pages/sessions.vue': {
      routes:
        | 'active-sessions'
      views:
        | never
    }
    'src/modules/user-management/pages/roles/create.vue': {
      routes:
        | 'create-role'
      views:
        | never
    }
    'src/modules/user-management/pages/roles/edit.vue': {
      routes:
        | 'edit-role'
      views:
        | never
    }
    'src/modules/user-management/pages/roles/list.vue': {
      routes:
        | 'roles-list'
      views:
        | never
    }
    'src/modules/user-management/pages/users/create.vue': {
      routes:
        | 'create-user'
      views:
        | never
    }
    'src/modules/user-management/pages/users/edit.vue': {
      routes:
        | 'users-edit'
      views:
        | never
    }
    'src/modules/user-management/pages/users/list.vue': {
      routes:
        | 'users-list'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
