// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:50:46.561Z
export interface IAiAgentConversation {
  id?: number;
  userId: number;
  title?: string;
  messages: Record<string, any>;
  context: string;
  status: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace AiAgentConversationFields {
  export const id = 'id';
  export const userId = 'userId';
  export const title = 'title';
  export const messages = 'messages';
  export const context = 'context';
  export const status = 'status';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
