// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T23:09:04.442Z
export interface IAiAgentOperation {
  id?: number;
  operationId: string;
  parameters: Record<string, any>;
  result: Record<string, any>;
  userId: number;
  source: string;
  conversationId?: number;
  duration: number;
  status: string;
  executedAt?: Date;
}

export namespace AiAgentOperationFields {
  export const id = 'id';
  export const operationId = 'operationId';
  export const parameters = 'parameters';
  export const result = 'result';
  export const userId = 'userId';
  export const source = 'source';
  export const conversationId = 'conversationId';
  export const duration = 'duration';
  export const status = 'status';
  export const executedAt = 'executedAt';
}
