// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T00:28:34.701Z
export interface IAiAgentSession {
  id?: number;
  visitorId: string;
  userId?: number;
  messages: Record<string, any>;
  memoryBuffer: Record<string, any>;
  agentState: Record<string, any>;
  status: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace AiAgentSessionFields {
  export const id = 'id';
  export const visitorId = 'visitorId';
  export const userId = 'userId';
  export const messages = 'messages';
  export const memoryBuffer = 'memoryBuffer';
  export const agentState = 'agentState';
  export const status = 'status';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
