// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T22:08:00.639Z
export interface IAuthEmailVerification {
  id: string;
  token: string;
  expiresAt: Date;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthEmailVerificationFields {
  export const id = 'id';
  export const token = 'token';
  export const expiresAt = 'expiresAt';
  export const userId = 'userId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
