// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T02:15:49.702Z
export interface IAuthHistory {
  id: number;
  login?: string;
  email?: string;
  password?: string;
  deviceData?: Record<string, any>;
  ispData?: Record<string, any>;
  result?: string;
  userId?: number;
  userName?: string;
  googleId?: string;
  avatar?: string;
  token: string;
  attemptTime?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace AuthHistoryFields {
  export const id = 'id';
  export const login = 'login';
  export const email = 'email';
  export const password = 'password';
  export const deviceData = 'deviceData';
  export const ispData = 'ispData';
  export const result = 'result';
  export const userId = 'userId';
  export const userName = 'userName';
  export const googleId = 'googleId';
  export const avatar = 'avatar';
  export const token = 'token';
  export const attemptTime = 'attemptTime';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
