// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:25:00.167Z
export interface IAuthPasswordReset {
  id: string;
  userId: number;
  token: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthPasswordResetFields {
  export const id = 'id';
  export const userId = 'userId';
  export const token = 'token';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
