// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:25:00.168Z
export interface IAuthUserRole {
  userId: number;
  roleId: number;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthUserRoleFields {
  export const userId = 'userId';
  export const roleId = 'roleId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
