// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:50:46.546Z
export interface IAuthRefreshToken {
  id: string;
  userId: number;
  token: string;
  accessTokenJti?: string;
  expiresAt: Date;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace AuthRefreshTokenFields {
  export const id = 'id';
  export const userId = 'userId';
  export const token = 'token';
  export const accessTokenJti = 'accessTokenJti';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
