// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T14:35:32.064Z
export interface IAuthVerificationCode {
  id: string;
  email: string;
  code: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthVerificationCodeFields {
  export const id = 'id';
  export const email = 'email';
  export const code = 'code';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
