// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T00:28:34.681Z
export interface IAuthRole {
  id: number;
  name: string;
  description: string;
  deleted?: boolean;
  abilityRules?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

export namespace AuthRoleFields {
  export const id = 'id';
  export const name = 'name';
  export const description = 'description';
  export const deleted = 'deleted';
  export const abilityRules = 'abilityRules';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
