// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T23:51:18.847Z
export interface IBlockExecution {
  id?: number;
  executionId: number;
  blockId: string;
  input?: Record<string, any>;
  output?: Record<string, any>;
  status: string;
  error?: any;
  startedAt?: Date;
  completedAt?: Date;
  duration?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace BlockExecutionFields {
  export const id = 'id';
  export const executionId = 'executionId';
  export const blockId = 'blockId';
  export const input = 'input';
  export const output = 'output';
  export const status = 'status';
  export const error = 'error';
  export const startedAt = 'startedAt';
  export const completedAt = 'completedAt';
  export const duration = 'duration';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
