// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-08-08T06:19:22.113Z
export interface IChannel {
  id?: number;
  name: string;
  type: string;
  config?: Record<string, any>;
  isActive?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace ChannelFields {
  export const id = 'id';
  export const name = 'name';
  export const type = 'type';
  export const config = 'config';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
