// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T21:50:19.428Z
export interface ICmsCategory {
  id: number;
  name: string;
  slug: string;
  parentId?: number;
  layout?: string;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
}

export namespace CmsCategoryFields {
  export const id = 'id';
  export const name = 'name';
  export const slug = 'slug';
  export const parentId = 'parentId';
  export const layout = 'layout';
  export const description = 'description';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
