// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T23:51:18.441Z
export interface ICmsItemMedia {
  itemId: number;
  mediaId: number;
  relationship: any;
  orderIndex?: number;
  createdAt: Date;
  updatedAt: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsItemMediaFields {
  export const itemId = 'itemId';
  export const mediaId = 'mediaId';
  export const relationship = 'relationship';
  export const orderIndex = 'orderIndex';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
