// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T02:15:46.096Z
export interface ICmsItem {
  id: number;
  title: string;
  slug: string;
  contentType: string;
  content?: string;
  status: string;
  layout?: string;
  sitePath: string;
  metadata?: Record<string, any>;
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string;
  canonicalUrl?: string;
  robotsMeta?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImageId?: number;
  schemaType?: string;
  structuredData?: Record<string, any>;
  sitemapPriority?: any;
  sitemapChangefreq?: string;
  includeInSitemap?: boolean;
  cacheEnabled?: boolean;
  cacheTtl?: number;
  cacheInfo?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  publishAt?: Date;
  scheduledBy?: number;
  isPublic: boolean;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsItemFields {
  export const id = 'id';
  export const title = 'title';
  export const slug = 'slug';
  export const contentType = 'contentType';
  export const content = 'content';
  export const status = 'status';
  export const layout = 'layout';
  export const sitePath = 'sitePath';
  export const metadata = 'metadata';
  export const metaTitle = 'metaTitle';
  export const metaDescription = 'metaDescription';
  export const metaKeywords = 'metaKeywords';
  export const canonicalUrl = 'canonicalUrl';
  export const robotsMeta = 'robotsMeta';
  export const ogTitle = 'ogTitle';
  export const ogDescription = 'ogDescription';
  export const ogImageId = 'ogImageId';
  export const schemaType = 'schemaType';
  export const structuredData = 'structuredData';
  export const sitemapPriority = 'sitemapPriority';
  export const sitemapChangefreq = 'sitemapChangefreq';
  export const includeInSitemap = 'includeInSitemap';
  export const cacheEnabled = 'cacheEnabled';
  export const cacheTtl = 'cacheTtl';
  export const cacheInfo = 'cacheInfo';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const publishedAt = 'publishedAt';
  export const publishAt = 'publishAt';
  export const scheduledBy = 'scheduledBy';
  export const isPublic = 'isPublic';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
