// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T21:50:19.434Z
export interface ICmsItemType {
  id: number;
  name: string;
  displayName: string;
  description?: string;
  schema?: Record<string, any>;
  icon?: string;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsItemTypeFields {
  export const id = 'id';
  export const name = 'name';
  export const displayName = 'displayName';
  export const description = 'description';
  export const schema = 'schema';
  export const icon = 'icon';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
