// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-06-07T05:10:58.462Z

export interface ICmsMenu {
  id: number;
  name: string;
  location: string;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsMenuFields {
  export const id = 'id';
  export const name = 'name';
  export const location = 'location';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
