// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:50:46.553Z
export interface ICmsMedia {
  id: number;
  filename: string;
  originalFilename: string;
  mimeType: string;
  size: number;
  path: string;
  altText?: string;
  title?: string;
  description?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsMediaFields {
  export const id = 'id';
  export const filename = 'filename';
  export const originalFilename = 'originalFilename';
  export const mimeType = 'mimeType';
  export const size = 'size';
  export const path = 'path';
  export const altText = 'altText';
  export const title = 'title';
  export const description = 'description';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
