// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-06-07T05:10:58.462Z

export interface ICmsMenuItem {
  id: number;
  title: string;
  menuId: number;
  url?: string;
  target?: string;
  orderIndex: number;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace CmsMenuItemFields {
  export const id = 'id';
  export const title = 'title';
  export const menuId = 'menuId';
  export const url = 'url';
  export const target = 'target';
  export const orderIndex = 'orderIndex';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
