// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T06:05:37.810Z
export interface ICompassItem {
  id: number;
  userId: number;
  type: string;
  approach?: string;
  parentId?: number;
  level: number;
  title: string;
  description?: any;
  status: string;
  deadline?: Date;
  startDate?: Date;
  completedAt?: Date;
  progress: number;
  metrics?: any;
  quarter?: string;
  phase?: string;
  position: number;
  tags?: any;
  priority?: string;
  workflowId?: number;
  executionType?: string;
  linkedPlanId?: number;
  partOfItemId?: number;
  aiAnalysis?: any;
  isCritical: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CompassItemFields {
  export const id = 'id';
  export const userId = 'userId';
  export const type = 'type';
  export const approach = 'approach';
  export const parentId = 'parentId';
  export const level = 'level';
  export const title = 'title';
  export const description = 'description';
  export const status = 'status';
  export const deadline = 'deadline';
  export const startDate = 'startDate';
  export const completedAt = 'completedAt';
  export const progress = 'progress';
  export const metrics = 'metrics';
  export const quarter = 'quarter';
  export const phase = 'phase';
  export const position = 'position';
  export const tags = 'tags';
  export const priority = 'priority';
  export const workflowId = 'workflowId';
  export const executionType = 'executionType';
  export const linkedPlanId = 'linkedPlanId';
  export const partOfItemId = 'partOfItemId';
  export const aiAnalysis = 'aiAnalysis';
  export const isCritical = 'isCritical';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
