// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T22:08:00.647Z
export interface IConfigPublic {
  id: number;
  key: string;
  value: any;
  category?: string;
  dataType?: string;
  description?: any;
  createdAt: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ConfigPublicFields {
  export const id = 'id';
  export const key = 'key';
  export const value = 'value';
  export const category = 'category';
  export const dataType = 'dataType';
  export const description = 'description';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
