// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-08-08T06:19:22.114Z
export interface IContact {
  id?: number;
  name: string;
  email?: string;
  phone?: string;
  newsletterStatus?: string;
  source?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace ContactFields {
  export const id = 'id';
  export const name = 'name';
  export const email = 'email';
  export const phone = 'phone';
  export const newsletterStatus = 'newsletterStatus';
  export const source = 'source';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
