// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-08-08T06:19:22.116Z
export interface IConversation {
  id?: number;
  contactId: number;
  subject: string;
  status?: string;
  priority?: string;
  assignedTo?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace ConversationFields {
  export const id = 'id';
  export const contactId = 'contactId';
  export const subject = 'subject';
  export const status = 'status';
  export const priority = 'priority';
  export const assignedTo = 'assignedTo';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
