// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T02:15:46.195Z
export interface ICrmChannel {
  id?: number;
  name: string;
  type: string;
  config?: Record<string, any>;
  isActive?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CrmChannelFields {
  export const id = 'id';
  export const name = 'name';
  export const type = 'type';
  export const config = 'config';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
