// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T02:15:46.195Z
export interface ICrmContact {
  id?: number;
  name: string;
  email?: string;
  phone?: string;
  newsletterStatus?: string;
  source?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CrmContactFields {
  export const id = 'id';
  export const name = 'name';
  export const email = 'email';
  export const phone = 'phone';
  export const newsletterStatus = 'newsletterStatus';
  export const source = 'source';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
