// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T06:28:31.258Z
export interface ICrmMessage {
  id?: number;
  conversationId: number;
  channelId?: number;
  type: string;
  direction: string;
  content: any;
  metadata?: Record<string, any>;
  status?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace CrmMessageFields {
  export const id = 'id';
  export const conversationId = 'conversationId';
  export const channelId = 'channelId';
  export const type = 'type';
  export const direction = 'direction';
  export const content = 'content';
  export const metadata = 'metadata';
  export const status = 'status';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
