// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T14:35:32.104Z
export interface ICrmTouchpoint {
  id?: number;
  contactId: number;
  source: string;
  channel?: string;
  action: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
}

export namespace CrmTouchpointFields {
  export const id = 'id';
  export const contactId = 'contactId';
  export const source = 'source';
  export const channel = 'channel';
  export const action = 'action';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
}
