// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T01:50:31.239Z
export interface IDispatcherTaskHistory {
  id: number;
  taskId?: number;
  parentId?: number;
  taskName?: string;
  taskType?: string;
  queueName?: string;
  status: string;
  externalJobId?: string;
  waitingSince?: Date;
  waitingUntil?: Date;
  startedAt: Date;
  finishedAt?: Date;
  duration?: number;
  error?: string;
  result?: Record<string, any>;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt: Date;
  createdBy?: number;
}

export namespace DispatcherTaskHistoryFields {
  export const id = 'id';
  export const taskId = 'taskId';
  export const parentId = 'parentId';
  export const taskName = 'taskName';
  export const taskType = 'taskType';
  export const queueName = 'queueName';
  export const status = 'status';
  export const externalJobId = 'externalJobId';
  export const waitingSince = 'waitingSince';
  export const waitingUntil = 'waitingUntil';
  export const startedAt = 'startedAt';
  export const finishedAt = 'finishedAt';
  export const duration = 'duration';
  export const error = 'error';
  export const result = 'result';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
}
