// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T22:08:00.646Z
export interface IDispatcherTask {
  id: number;
  name: string;
  type: string;
  data?: Record<string, any>;
  periodSec?: number;
  parentId?: number;
  isActive: boolean;
  lastRun?: Date;
  lastStatus?: string;
  lastError?: string;
  maxRuns?: number;
  runCount?: number;
  nextRun?: Date;
  scheduleType?: string;
  cronExpr?: string;
  timeout?: number;
  retryCount?: number;
  retryDelay?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace DispatcherTaskFields {
  export const id = 'id';
  export const name = 'name';
  export const type = 'type';
  export const data = 'data';
  export const periodSec = 'periodSec';
  export const parentId = 'parentId';
  export const isActive = 'isActive';
  export const lastRun = 'lastRun';
  export const lastStatus = 'lastStatus';
  export const lastError = 'lastError';
  export const maxRuns = 'maxRuns';
  export const runCount = 'runCount';
  export const nextRun = 'nextRun';
  export const scheduleType = 'scheduleType';
  export const cronExpr = 'cronExpr';
  export const timeout = 'timeout';
  export const retryCount = 'retryCount';
  export const retryDelay = 'retryDelay';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
