// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T02:15:46.097Z
export interface IDispatcherQueueTask {
  id: number;
  queue: string;
  type: string;
  name: string;
  data: Record<string, any>;
  status: string;
  priority: number;
  attempts: number;
  maxAttempts: number;
  error?: string;
  createdAt: Date;
  updatedAt: Date;
  processedAt?: Date;
}

export namespace DispatcherQueueTaskFields {
  export const id = 'id';
  export const queue = 'queue';
  export const type = 'type';
  export const name = 'name';
  export const data = 'data';
  export const status = 'status';
  export const priority = 'priority';
  export const attempts = 'attempts';
  export const maxAttempts = 'maxAttempts';
  export const error = 'error';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const processedAt = 'processedAt';
}
