// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2026-09-05T15:57:44.112Z
export interface IFeedbackMessage {
  id: number;
  subject: string;
  body: string;
  rating: number;
  status: string;
  userId: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace FeedbackMessageFields {
  export const id = 'id';
  export const subject = 'subject';
  export const body = 'body';
  export const rating = 'rating';
  export const status = 'status';
  export const userId = 'userId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
