// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-11-02T21:53:47.352Z
export interface IFluxUpload {
  id: number;
  fileName: string;
  originalName: string;
  mimeType: string;
  size: number;
  url: string;
  isActive: boolean;
  createdAt?: Date;
  updatedAt: Date;
}

export namespace FluxUploadFields {
  export const id = 'id';
  export const fileName = 'fileName';
  export const originalName = 'originalName';
  export const mimeType = 'mimeType';
  export const size = 'size';
  export const url = 'url';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
