// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-09-08T02:59:43.696Z
export interface IFluxJob {
  id: number;
  prompt: string;
  width: number;
  height: number;
  steps: number;
  guidance: any;
  seed?: number;
  inputImageUrl?: string;
  outputImageUrl?: string;
  status: string;
  cost: any;
  mp: any;
  model: string;
  errorMessage?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  completedAt?: Date;
  updatedAt: Date;
}

export namespace FluxJobFields {
  export const id = 'id';
  export const prompt = 'prompt';
  export const width = 'width';
  export const height = 'height';
  export const steps = 'steps';
  export const guidance = 'guidance';
  export const seed = 'seed';
  export const inputImageUrl = 'inputImageUrl';
  export const outputImageUrl = 'outputImageUrl';
  export const status = 'status';
  export const cost = 'cost';
  export const mp = 'mp';
  export const model = 'model';
  export const errorMessage = 'errorMessage';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const completedAt = 'completedAt';
  export const updatedAt = 'updatedAt';
}
