// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T21:03:01.970Z
export interface IImageUpload {
  id: number;
  fileName: string;
  originalName: string;
  mimeType: string;
  size: number;
  url: string;
  isActive: boolean;
  createdAt?: Date;
  createdBy?: number;
  updatedAt?: Date;
  updatedBy?: number;
}

export namespace ImageUploadFields {
  export const id = 'id';
  export const fileName = 'fileName';
  export const originalName = 'originalName';
  export const mimeType = 'mimeType';
  export const size = 'size';
  export const url = 'url';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const createdBy = 'createdBy';
  export const updatedAt = 'updatedAt';
  export const updatedBy = 'updatedBy';
}
