// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T15:35:36.305Z
export interface IKnowledgeDocument {
  id?: number;
  siteId?: string;
  category: string;
  key: string;
  title: string;
  content: any;
  structuredView?: any;
  metadata?: Record<string, any>;
  tags?: Record<string, any>;
  source?: string;
  scannedAt?: Date;
  isActive?: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export namespace KnowledgeDocumentFields {
  export const id = 'id';
  export const siteId = 'siteId';
  export const category = 'category';
  export const key = 'key';
  export const title = 'title';
  export const content = 'content';
  export const structuredView = 'structuredView';
  export const metadata = 'metadata';
  export const tags = 'tags';
  export const source = 'source';
  export const scannedAt = 'scannedAt';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
