// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-08-08T06:19:22.116Z
export interface IMessage {
  id?: number;
  conversationId: number;
  channelId?: number;
  type: string;
  direction: string;
  content: any;
  metadata?: Record<string, any>;
  status?: string;
  createdAt?: Date;
}

export namespace MessageFields {
  export const id = 'id';
  export const conversationId = 'conversationId';
  export const channelId = 'channelId';
  export const type = 'type';
  export const direction = 'direction';
  export const content = 'content';
  export const metadata = 'metadata';
  export const status = 'status';
  export const createdAt = 'createdAt';
}
