// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T02:56:51.528Z
export interface INewsletterSubscription {
  id?: number;
  email: string;
  name?: string;
  status?: string;
  isActive?: boolean;
  source?: string;
  tags?: Record<string, any>;
  unsubscribeToken?: string;
  unsubscribedAt?: Date;
  ipAddress?: string;
  userAgent?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace NewsletterSubscriptionFields {
  export const id = 'id';
  export const email = 'email';
  export const name = 'name';
  export const status = 'status';
  export const isActive = 'isActive';
  export const source = 'source';
  export const tags = 'tags';
  export const unsubscribeToken = 'unsubscribeToken';
  export const unsubscribedAt = 'unsubscribedAt';
  export const ipAddress = 'ipAddress';
  export const userAgent = 'userAgent';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
