// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-08-06T14:52:00.534Z
export interface INewsletter {
  id?: number;
  email: string;
  name?: string;
  isActive?: boolean;
  source?: string;
  ipAddress?: string;
  userAgent?: string;
  createdAt?: Date;
}

export namespace NewsletterFields {
  export const id = 'id';
  export const email = 'email';
  export const name = 'name';
  export const isActive = 'isActive';
  export const source = 'source';
  export const ipAddress = 'ipAddress';
  export const userAgent = 'userAgent';
  export const createdAt = 'createdAt';
}
