// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T23:51:18.781Z
export interface INewsletterEmailLog {
  id?: number;
  campaignId: number;
  subscriptionId: number;
  email: string;
  status?: string;
  sentAt?: Date;
  openedAt?: Date;
  clickedAt?: Date;
  errorMessage?: any;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace NewsletterEmailLogFields {
  export const id = 'id';
  export const campaignId = 'campaignId';
  export const subscriptionId = 'subscriptionId';
  export const email = 'email';
  export const status = 'status';
  export const sentAt = 'sentAt';
  export const openedAt = 'openedAt';
  export const clickedAt = 'clickedAt';
  export const errorMessage = 'errorMessage';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
