// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T15:35:36.318Z
export interface INewsletterCampaign {
  id?: number;
  name: string;
  templateId: number;
  status?: string;
  recipientFilter?: Record<string, any>;
  totalRecipients?: number;
  sentCount?: number;
  failedCount?: number;
  openCount?: number;
  clickCount?: number;
  scheduledAt?: Date;
  startedAt?: Date;
  completedAt?: Date;
  createdBy?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace NewsletterCampaignFields {
  export const id = 'id';
  export const name = 'name';
  export const templateId = 'templateId';
  export const status = 'status';
  export const recipientFilter = 'recipientFilter';
  export const totalRecipients = 'totalRecipients';
  export const sentCount = 'sentCount';
  export const failedCount = 'failedCount';
  export const openCount = 'openCount';
  export const clickCount = 'clickCount';
  export const scheduledAt = 'scheduledAt';
  export const startedAt = 'startedAt';
  export const completedAt = 'completedAt';
  export const createdBy = 'createdBy';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
