// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T02:56:51.527Z
export interface INewsletterTemplate {
  id?: number;
  name: string;
  subject: string;
  previewText?: string;
  htmlContent: string;
  textContent?: string;
  status?: string;
  category?: string;
  variables?: Record<string, any>;
  createdBy?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace NewsletterTemplateFields {
  export const id = 'id';
  export const name = 'name';
  export const subject = 'subject';
  export const previewText = 'previewText';
  export const htmlContent = 'htmlContent';
  export const textContent = 'textContent';
  export const status = 'status';
  export const category = 'category';
  export const variables = 'variables';
  export const createdBy = 'createdBy';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
