// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T15:35:36.262Z
export interface INotificationsHistory {
  id: number;
  userId: number;
  type: string;
  message: any;
  status: string;
  metadata?: Record<string, any>;
  templateId?: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace NotificationsHistoryFields {
  export const id = 'id';
  export const userId = 'userId';
  export const type = 'type';
  export const message = 'message';
  export const status = 'status';
  export const metadata = 'metadata';
  export const templateId = 'templateId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
