// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T21:06:34.982Z
export interface INotificationsTelegramUser {
  id: number;
  phone: string;
  chatId: string;
  username?: string;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace NotificationsTelegramUserFields {
  export const id = 'id';
  export const phone = 'phone';
  export const chatId = 'chatId';
  export const username = 'username';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
