// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T22:33:13.764Z
export interface INotificationsTemplate {
  id: number;
  name: string;
  subject: string;
  body: any;
  notificationType: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace NotificationsTemplateFields {
  export const id = 'id';
  export const name = 'name';
  export const subject = 'subject';
  export const body = 'body';
  export const notificationType = 'notificationType';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
