// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T23:51:18.781Z
export interface IPaymentProduct {
  id?: number;
  productId: string;
  name: string;
  description?: any;
  type: string;
  price: any;
  tokenGrant?: number;
  bonus?: number;
  popular: boolean;
  featured: boolean;
  stripePriceId?: string;
  active: boolean;
  sortOrder: number;
  imageUrl?: string;
  featureAccess?: Record<string, any>;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentProductFields {
  export const id = 'id';
  export const productId = 'productId';
  export const name = 'name';
  export const description = 'description';
  export const type = 'type';
  export const price = 'price';
  export const tokenGrant = 'tokenGrant';
  export const bonus = 'bonus';
  export const popular = 'popular';
  export const featured = 'featured';
  export const stripePriceId = 'stripePriceId';
  export const active = 'active';
  export const sortOrder = 'sortOrder';
  export const imageUrl = 'imageUrl';
  export const featureAccess = 'featureAccess';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
