// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T02:15:49.731Z
export interface IPaymentPricingTierConfig {
  id?: number;
  tier: string;
  name: string;
  description?: any;
  price: any;
  interval: string;
  tokenGrant: number;
  tokenRefill: number;
  rollover: boolean;
  features?: Record<string, any>;
  stripePriceId?: string;
  active: boolean;
  sortOrder: number;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentPricingTierConfigFields {
  export const id = 'id';
  export const tier = 'tier';
  export const name = 'name';
  export const description = 'description';
  export const price = 'price';
  export const interval = 'interval';
  export const tokenGrant = 'tokenGrant';
  export const tokenRefill = 'tokenRefill';
  export const rollover = 'rollover';
  export const features = 'features';
  export const stripePriceId = 'stripePriceId';
  export const active = 'active';
  export const sortOrder = 'sortOrder';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
