// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T06:28:31.265Z
export interface IPaymentUsageLog {
  id?: number;
  userId: number;
  resourceType: string;
  amount: number;
  endpoint?: string;
  metadata?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

export namespace PaymentUsageLogFields {
  export const id = 'id';
  export const userId = 'userId';
  export const resourceType = 'resourceType';
  export const amount = 'amount';
  export const endpoint = 'endpoint';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
