// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T22:08:00.652Z
export interface IPaymentTokenTransaction {
  id?: number;
  userId: number;
  subscriptionId?: number;
  amount: number;
  balanceAfter: number;
  type: string;
  reason: string;
  referenceId?: string;
  idempotencyKey?: string;
  stripePaymentIntentId?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentTokenTransactionFields {
  export const id = 'id';
  export const userId = 'userId';
  export const subscriptionId = 'subscriptionId';
  export const amount = 'amount';
  export const balanceAfter = 'balanceAfter';
  export const type = 'type';
  export const reason = 'reason';
  export const referenceId = 'referenceId';
  export const idempotencyKey = 'idempotencyKey';
  export const stripePaymentIntentId = 'stripePaymentIntentId';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
