// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T20:46:05.962Z
export interface IPaymentUsageQuota {
  id?: number;
  userId: number;
  resourceType: string;
  quotaLimit: number;
  currentUsage: number;
  resetAt: Date;
  tier: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentUsageQuotaFields {
  export const id = 'id';
  export const userId = 'userId';
  export const resourceType = 'resourceType';
  export const quotaLimit = 'quotaLimit';
  export const currentUsage = 'currentUsage';
  export const resetAt = 'resetAt';
  export const tier = 'tier';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
