// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T05:19:00.686Z
export interface IPaymentSubscription {
  id?: number;
  userId: number;
  tier: string;
  tokenBalance: number;
  status: string;
  expiresAt?: Date;
  cancelledAt?: Date;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentSubscriptionFields {
  export const id = 'id';
  export const userId = 'userId';
  export const tier = 'tier';
  export const tokenBalance = 'tokenBalance';
  export const status = 'status';
  export const expiresAt = 'expiresAt';
  export const cancelledAt = 'cancelledAt';
  export const stripeCustomerId = 'stripeCustomerId';
  export const stripeSubscriptionId = 'stripeSubscriptionId';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
