// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T21:06:34.987Z
export interface IPaymentFeatureCost {
  id?: number;
  featureId: string;
  name: string;
  description?: any;
  pluginId: string;
  defaultCost: number;
  tierCosts?: Record<string, any>;
  category?: string;
  active: boolean;
  minimumTier?: string;
  trackUsage: boolean;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PaymentFeatureCostFields {
  export const id = 'id';
  export const featureId = 'featureId';
  export const name = 'name';
  export const description = 'description';
  export const pluginId = 'pluginId';
  export const defaultCost = 'defaultCost';
  export const tierCosts = 'tierCosts';
  export const category = 'category';
  export const active = 'active';
  export const minimumTier = 'minimumTier';
  export const trackUsage = 'trackUsage';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
