// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T01:50:31.249Z
export interface IPhotoshootImage {
  id: number;
  sessionId: number;
  styleConfig: Record<string, any>;
  storageFileId?: string;
  taskHistoryId?: number;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PhotoshootImageFields {
  export const id = 'id';
  export const sessionId = 'sessionId';
  export const styleConfig = 'styleConfig';
  export const storageFileId = 'storageFileId';
  export const taskHistoryId = 'taskHistoryId';
  export const status = 'status';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
