// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T00:28:34.726Z
export interface IPhotoshootSession {
  id: number;
  userId: number;
  packageConfig: Record<string, any>;
  uploadedPhotoIds: Record<string, any>;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  totalImages: number;
  completedImages: number;
  taskIds: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace PhotoshootSessionFields {
  export const id = 'id';
  export const userId = 'userId';
  export const packageConfig = 'packageConfig';
  export const uploadedPhotoIds = 'uploadedPhotoIds';
  export const status = 'status';
  export const totalImages = 'totalImages';
  export const completedImages = 'completedImages';
  export const taskIds = 'taskIds';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
