// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T01:50:31.250Z
export interface IProjectActivity {
  id: number;
  projectId: number;
  taskId?: number;
  entityType: string;
  action: string;
  field?: string;
  oldValue?: any;
  newValue?: any;
  description?: any;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
}

export namespace ProjectActivityFields {
  export const id = 'id';
  export const projectId = 'projectId';
  export const taskId = 'taskId';
  export const entityType = 'entityType';
  export const action = 'action';
  export const field = 'field';
  export const oldValue = 'oldValue';
  export const newValue = 'newValue';
  export const description = 'description';
  export const userId = 'userId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
