// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:25:00.244Z
export interface IProject {
  id: number;
  name: string;
  slug: string;
  description?: string;
  status: string;
  priority?: string;
  startDate?: Date;
  deadline?: Date;
  completedAt?: Date;
  color?: string;
  ownerId: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ProjectFields {
  export const id = 'id';
  export const name = 'name';
  export const slug = 'slug';
  export const description = 'description';
  export const status = 'status';
  export const priority = 'priority';
  export const startDate = 'startDate';
  export const deadline = 'deadline';
  export const completedAt = 'completedAt';
  export const color = 'color';
  export const ownerId = 'ownerId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
