// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T06:05:37.820Z
export interface IProjectTask {
  id: number;
  projectId: number;
  parentTaskId?: number;
  title: string;
  description?: any;
  status: string;
  priority: string;
  assigneeId?: number;
  deadline?: Date;
  completedAt?: Date;
  estimatedHours?: any;
  actualHours?: any;
  position?: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ProjectTaskFields {
  export const id = 'id';
  export const projectId = 'projectId';
  export const parentTaskId = 'parentTaskId';
  export const title = 'title';
  export const description = 'description';
  export const status = 'status';
  export const priority = 'priority';
  export const assigneeId = 'assigneeId';
  export const deadline = 'deadline';
  export const completedAt = 'completedAt';
  export const estimatedHours = 'estimatedHours';
  export const actualHours = 'actualHours';
  export const position = 'position';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
