// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T23:09:04.393Z
export interface IServerContainer {
  id: number;
  name: string;
  projectId: number;
  status: string;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace ServerContainerFields {
  export const id = 'id';
  export const name = 'name';
  export const projectId = 'projectId';
  export const status = 'status';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
