// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T02:15:49.735Z
export interface ISocialPostTemplate {
  id: number;
  name: string;
  description?: string;
  platformId: string;
  userId: number;
  content: string;
  hashtags?: Record<string, any>;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace SocialPostTemplateFields {
  export const id = 'id';
  export const name = 'name';
  export const description = 'description';
  export const platformId = 'platformId';
  export const userId = 'userId';
  export const content = 'content';
  export const hashtags = 'hashtags';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
