// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T20:46:05.967Z
export interface ISocialPostAnalytics {
  id: number;
  postId: number;
  platformId: string;
  likes?: number;
  shares?: number;
  comments?: number;
  views?: number;
  clicks?: number;
  metadata?: Record<string, any>;
  lastUpdated?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export namespace SocialPostAnalyticsFields {
  export const id = 'id';
  export const postId = 'postId';
  export const platformId = 'platformId';
  export const likes = 'likes';
  export const shares = 'shares';
  export const comments = 'comments';
  export const views = 'views';
  export const clicks = 'clicks';
  export const metadata = 'metadata';
  export const lastUpdated = 'lastUpdated';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
