// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T02:15:46.256Z
export interface ISocialPost {
  id: number;
  platformId: string;
  accountId: number;
  userId: number;
  content: string;
  mediaIds?: Record<string, any>;
  hashtags?: Record<string, any>;
  status: string;
  scheduledAt?: Date;
  publishedAt?: Date;
  externalPostId?: string;
  externalUrl?: string;
  metadata?: Record<string, any>;
  errorMessage?: string;
  retryCount?: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SocialPostFields {
  export const id = 'id';
  export const platformId = 'platformId';
  export const accountId = 'accountId';
  export const userId = 'userId';
  export const content = 'content';
  export const mediaIds = 'mediaIds';
  export const hashtags = 'hashtags';
  export const status = 'status';
  export const scheduledAt = 'scheduledAt';
  export const publishedAt = 'publishedAt';
  export const externalPostId = 'externalPostId';
  export const externalUrl = 'externalUrl';
  export const metadata = 'metadata';
  export const errorMessage = 'errorMessage';
  export const retryCount = 'retryCount';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
