// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:50:46.626Z
export interface ISocialPostMedia {
  postId: number;
  mediaId: number;
  orderIndex?: number;
  createdAt: Date;
  updatedAt: Date;
}

export namespace SocialPostMediaFields {
  export const postId = 'postId';
  export const mediaId = 'mediaId';
  export const orderIndex = 'orderIndex';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
