// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T18:47:33.223Z
export interface ISocialAccount {
  id: number;
  platformId: string;
  userId: number;
  accountName: string;
  accountHandle: string;
  accountId: string;
  accessToken: string;
  refreshToken?: string;
  tokenExpiresAt?: Date;
  isActive: boolean;
  lastSync?: Date;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace SocialAccountFields {
  export const id = 'id';
  export const platformId = 'platformId';
  export const userId = 'userId';
  export const accountName = 'accountName';
  export const accountHandle = 'accountHandle';
  export const accountId = 'accountId';
  export const accessToken = 'accessToken';
  export const refreshToken = 'refreshToken';
  export const tokenExpiresAt = 'tokenExpiresAt';
  export const isActive = 'isActive';
  export const lastSync = 'lastSync';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
