// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T00:28:34.727Z
export interface ISocialPlatform {
  id: string;
  name: string;
  displayName: string;
  icon?: string;
  maxTextLength?: number;
  supportedMediaTypes?: Record<string, any>;
  features?: Record<string, any>;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace SocialPlatformFields {
  export const id = 'id';
  export const name = 'name';
  export const displayName = 'displayName';
  export const icon = 'icon';
  export const maxTextLength = 'maxTextLength';
  export const supportedMediaTypes = 'supportedMediaTypes';
  export const features = 'features';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
