// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T22:08:00.647Z
export interface IStorageFile {
  id: string;
  originalName: string;
  fileName: string;
  mimeType: string;
  size: number;
  storageProvider: string;
  storagePath: string;
  publicUrl?: string;
  visibility: string;
  userId: number;
  moduleContext?: string;
  contextId?: string;
  tags?: Record<string, any>;
  description?: string;
  status: string;
  expiresAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

export namespace StorageFileFields {
  export const id = 'id';
  export const originalName = 'originalName';
  export const fileName = 'fileName';
  export const mimeType = 'mimeType';
  export const size = 'size';
  export const storageProvider = 'storageProvider';
  export const storagePath = 'storagePath';
  export const publicUrl = 'publicUrl';
  export const visibility = 'visibility';
  export const userId = 'userId';
  export const moduleContext = 'moduleContext';
  export const contextId = 'contextId';
  export const tags = 'tags';
  export const description = 'description';
  export const status = 'status';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const deletedAt = 'deletedAt';
}
