// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T00:28:34.691Z
export interface ISystemConfigAudit {
  id: number;
  configKey: string;
  oldValue?: any;
  newValue?: any;
  changedBy?: number;
  changeSource: string;
  ipAddress?: string;
  userAgent?: any;
  createdAt: Date;
  updatedAt: Date;
}

export namespace SystemConfigAuditFields {
  export const id = 'id';
  export const configKey = 'configKey';
  export const oldValue = 'oldValue';
  export const newValue = 'newValue';
  export const changedBy = 'changedBy';
  export const changeSource = 'changeSource';
  export const ipAddress = 'ipAddress';
  export const userAgent = 'userAgent';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
