// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T23:51:18.585Z
export interface ISystemSessionStorage {
  id: number;
  key: string;
  value: any;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export namespace SystemSessionStorageFields {
  export const id = 'id';
  export const key = 'key';
  export const value = 'value';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
