// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T21:03:01.968Z
export interface ISystemError {
  id: number;
  logId: number;
  errorType: string;
  errorMessage: any;
  stackTrace?: any;
  additionalData?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemErrorFields {
  export const id = 'id';
  export const logId = 'logId';
  export const errorType = 'errorType';
  export const errorMessage = 'errorMessage';
  export const stackTrace = 'stackTrace';
  export const additionalData = 'additionalData';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
