// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T02:15:49.714Z
export interface ISystemDynamicRoute {
  id: string;
  path: string;
  name: string;
  component?: string;
  parentId?: string;
  orderIndex: number;
  meta?: Record<string, any>;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemDynamicRouteFields {
  export const id = 'id';
  export const path = 'path';
  export const name = 'name';
  export const component = 'component';
  export const parentId = 'parentId';
  export const orderIndex = 'orderIndex';
  export const meta = 'meta';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
