// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T06:05:37.807Z
export interface ISystemLog {
  id: number;
  timestamp: Date;
  level: string;
  source: string;
  component: string;
  module: string;
  message: any;
  metadata?: Record<string, any>;
  contextId?: string;
  userId?: string;
  ipAddress?: string;
  requestPath?: string;
  requestMethod?: string;
  executionTime?: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemLogFields {
  export const id = 'id';
  export const timestamp = 'timestamp';
  export const level = 'level';
  export const source = 'source';
  export const component = 'component';
  export const module = 'module';
  export const message = 'message';
  export const metadata = 'metadata';
  export const contextId = 'contextId';
  export const userId = 'userId';
  export const ipAddress = 'ipAddress';
  export const requestPath = 'requestPath';
  export const requestMethod = 'requestMethod';
  export const executionTime = 'executionTime';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
