// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T05:19:00.681Z
export interface ISystemLogStat {
  id: number;
  date: Date;
  hour: number;
  source: string;
  module: string;
  level: string;
  count: number;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemLogStatFields {
  export const id = 'id';
  export const date = 'date';
  export const hour = 'hour';
  export const source = 'source';
  export const module = 'module';
  export const level = 'level';
  export const count = 'count';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
