// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:25:00.234Z
export interface ISystemCache {
  id: number;
  key: string;
  value: string;
  namespace?: string;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt?: Date;
}

export namespace SystemCacheFields {
  export const id = 'id';
  export const key = 'key';
  export const value = 'value';
  export const namespace = 'namespace';
  export const expiresAt = 'expiresAt';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
