// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:25:00.234Z
export interface ISystemConfig {
  id: number;
  key: string;
  value: string;
  category?: string;
  dataType?: string;
  isEncrypted?: boolean;
  requiresRestart?: boolean;
  description?: string;
  createdAt: Date;
  updatedAt?: Date;
  createdBy?: number;
  updatedBy?: number;
}

export namespace SystemConfigFields {
  export const id = 'id';
  export const key = 'key';
  export const value = 'value';
  export const category = 'category';
  export const dataType = 'dataType';
  export const isEncrypted = 'isEncrypted';
  export const requiresRestart = 'requiresRestart';
  export const description = 'description';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const createdBy = 'createdBy';
  export const updatedBy = 'updatedBy';
}
