// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T02:56:51.533Z
export interface ITestItem {
  id: number;
  title: string;
  description?: string;
  count?: number;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace TestItemFields {
  export const id = 'id';
  export const title = 'title';
  export const description = 'description';
  export const count = 'count';
  export const isActive = 'isActive';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
