// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T14:35:32.133Z
export interface IWaitlistReferral {
  id: number;
  referrerId: number;
  referredEmail: string;
  status: string;
  clickedAt: Date;
  signedUpAt?: Date;
  verifiedAt?: Date;
  metadata?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

export namespace WaitlistReferralFields {
  export const id = 'id';
  export const referrerId = 'referrerId';
  export const referredEmail = 'referredEmail';
  export const status = 'status';
  export const clickedAt = 'clickedAt';
  export const signedUpAt = 'signedUpAt';
  export const verifiedAt = 'verifiedAt';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
