// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T21:31:24.650Z
export interface IWaitlistSignup {
  id: number;
  email: string;
  name?: string;
  status: string;
  position: number;
  referralCode: string;
  referredById?: number;
  referralCount: number;
  positionBoost: number;
  verificationToken?: string;
  verificationTokenExpiry?: Date;
  newsletterConsent: boolean;
  metadata?: Record<string, any>;
  verifiedAt?: Date;
  invitedAt?: Date;
  unsubscribedAt?: Date;
  userId?: number;
  contactId?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WaitlistSignupFields {
  export const id = 'id';
  export const email = 'email';
  export const name = 'name';
  export const status = 'status';
  export const position = 'position';
  export const referralCode = 'referralCode';
  export const referredById = 'referredById';
  export const referralCount = 'referralCount';
  export const positionBoost = 'positionBoost';
  export const verificationToken = 'verificationToken';
  export const verificationTokenExpiry = 'verificationTokenExpiry';
  export const newsletterConsent = 'newsletterConsent';
  export const metadata = 'metadata';
  export const verifiedAt = 'verifiedAt';
  export const invitedAt = 'invitedAt';
  export const unsubscribedAt = 'unsubscribedAt';
  export const userId = 'userId';
  export const contactId = 'contactId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
