// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-17T03:25:00.248Z
export interface IWebAnalyticsVisit {
  id: string;
  sessionId: string;
  userId?: number;
  ipAddressHash: string;
  userAgent: string;
  deviceType: string;
  browserName?: string;
  browserVersion?: string;
  osName?: string;
  osVersion?: string;
  firstVisitAt: Date;
  lastActivityAt: Date;
  durationSeconds: number;
  entryPage: string;
  exitPage?: string;
  pageViewsCount: number;
  referrerUrl?: string;
  referrerDomain?: string;
  channel?: string;
  utmSource?: string;
  utmMedium?: string;
  utmCampaign?: string;
  utmTerm?: string;
  utmContent?: string;
  isBounce: boolean;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WebAnalyticsVisitFields {
  export const id = 'id';
  export const sessionId = 'sessionId';
  export const userId = 'userId';
  export const ipAddressHash = 'ipAddressHash';
  export const userAgent = 'userAgent';
  export const deviceType = 'deviceType';
  export const browserName = 'browserName';
  export const browserVersion = 'browserVersion';
  export const osName = 'osName';
  export const osVersion = 'osVersion';
  export const firstVisitAt = 'firstVisitAt';
  export const lastActivityAt = 'lastActivityAt';
  export const durationSeconds = 'durationSeconds';
  export const entryPage = 'entryPage';
  export const exitPage = 'exitPage';
  export const pageViewsCount = 'pageViewsCount';
  export const referrerUrl = 'referrerUrl';
  export const referrerDomain = 'referrerDomain';
  export const channel = 'channel';
  export const utmSource = 'utmSource';
  export const utmMedium = 'utmMedium';
  export const utmCampaign = 'utmCampaign';
  export const utmTerm = 'utmTerm';
  export const utmContent = 'utmContent';
  export const isBounce = 'isBounce';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
