// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T05:19:00.690Z
export interface IWebAnalyticsReferrer {
  id: number;
  referrerUrl: string;
  referrerDomain: string;
  channel: string;
  visits: number;
  uniqueVisitors: number;
  pageViews: number;
  avgSessionDuration: number;
  bounceRate: any;
  avgPagesPerVisit: any;
  firstSeenAt: Date;
  lastSeenAt: Date;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WebAnalyticsReferrerFields {
  export const id = 'id';
  export const referrerUrl = 'referrerUrl';
  export const referrerDomain = 'referrerDomain';
  export const channel = 'channel';
  export const visits = 'visits';
  export const uniqueVisitors = 'uniqueVisitors';
  export const pageViews = 'pageViews';
  export const avgSessionDuration = 'avgSessionDuration';
  export const bounceRate = 'bounceRate';
  export const avgPagesPerVisit = 'avgPagesPerVisit';
  export const firstSeenAt = 'firstSeenAt';
  export const lastSeenAt = 'lastSeenAt';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
