// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-16T06:28:31.268Z
export interface IWebAnalyticsPageView {
  id: string;
  visitId: string;
  sessionId: string;
  userId?: number;
  source: string;
  path: string;
  queryParams?: Record<string, any>;
  referrerUrl?: string;
  referrerPath?: string;
  viewedAt: Date;
  userAgent: string;
  ipAddressHash: string;
  httpStatus?: number;
  requestTimeMs?: number;
  screenResolution?: string;
  pageTitle?: string;
  timeOnPageSeconds?: number;
  metadata?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WebAnalyticsPageViewFields {
  export const id = 'id';
  export const visitId = 'visitId';
  export const sessionId = 'sessionId';
  export const userId = 'userId';
  export const source = 'source';
  export const path = 'path';
  export const queryParams = 'queryParams';
  export const referrerUrl = 'referrerUrl';
  export const referrerPath = 'referrerPath';
  export const viewedAt = 'viewedAt';
  export const userAgent = 'userAgent';
  export const ipAddressHash = 'ipAddressHash';
  export const httpStatus = 'httpStatus';
  export const requestTimeMs = 'requestTimeMs';
  export const screenResolution = 'screenResolution';
  export const pageTitle = 'pageTitle';
  export const timeOnPageSeconds = 'timeOnPageSeconds';
  export const metadata = 'metadata';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
