// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T21:06:34.993Z
export interface IWorkflowDefinition {
  id?: number;
  name: string;
  description?: any;
  userPrompt?: any;
  masterPrompt?: any;
  version: number;
  blocks: Record<string, any>;
  connections: Record<string, any>;
  status: string;
  triggerType: string;
  triggerConfig?: Record<string, any>;
  tags?: Record<string, any>;
  isActive: boolean;
  createdBy: number;
  createdAt?: Date;
  updatedAt?: Date;
  publishedAt?: Date;
}

export namespace WorkflowDefinitionFields {
  export const id = 'id';
  export const name = 'name';
  export const description = 'description';
  export const userPrompt = 'userPrompt';
  export const masterPrompt = 'masterPrompt';
  export const version = 'version';
  export const blocks = 'blocks';
  export const connections = 'connections';
  export const status = 'status';
  export const triggerType = 'triggerType';
  export const triggerConfig = 'triggerConfig';
  export const tags = 'tags';
  export const isActive = 'isActive';
  export const createdBy = 'createdBy';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
  export const publishedAt = 'publishedAt';
}
