// THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
// Generated by DSL Generator on 2025-12-15T02:15:49.739Z
export interface IWorkflowExecution {
  id?: number;
  workflowId: number;
  status: string;
  currentBlocks?: Record<string, any>;
  completedBlocks?: Record<string, any>;
  failedBlocks?: Record<string, any>;
  progress: number;
  blockResults?: Record<string, any>;
  logs?: Record<string, any>;
  context?: Record<string, any>;
  startedAt?: Date;
  completedAt?: Date;
  pausedAt?: Date;
  error?: any;
  errorDetails?: Record<string, any>;
  triggeredBy?: number;
  triggerSource: string;
  retryCount: number;
  parentExecutionId?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export namespace WorkflowExecutionFields {
  export const id = 'id';
  export const workflowId = 'workflowId';
  export const status = 'status';
  export const currentBlocks = 'currentBlocks';
  export const completedBlocks = 'completedBlocks';
  export const failedBlocks = 'failedBlocks';
  export const progress = 'progress';
  export const blockResults = 'blockResults';
  export const logs = 'logs';
  export const context = 'context';
  export const startedAt = 'startedAt';
  export const completedAt = 'completedAt';
  export const pausedAt = 'pausedAt';
  export const error = 'error';
  export const errorDetails = 'errorDetails';
  export const triggeredBy = 'triggeredBy';
  export const triggerSource = 'triggerSource';
  export const retryCount = 'retryCount';
  export const parentExecutionId = 'parentExecutionId';
  export const createdAt = 'createdAt';
  export const updatedAt = 'updatedAt';
}
